### ISSUE TITLE
Update Contact: Company not updating

### ISSUE THREAD

**Issue by vidyesh-phases** [microsoftgraph/msgraph-sdk-dotnet#502] opened 2019-06-26 16:05 UTC
### Expected behavior
Company name needs to be updated with the given value.

### Actual behavior
When updating existing contacts having company as null is not getting updated.
When tried using the Graph explorer it seems to be working.
After updating using the graph explorer the sdk seems to work well.

### Steps to reproduce the behavior

1. Select a contact without Company Name (companyName = **null**).
2. Call the **UpdateAsync** request for a contact / people item.

`await graphClient.Me.Contacts[contact.Id].Request(requestOptions).WithUserAccount(account).UpdateAsync(contact);`

3. Setting companyName = null also not removing the value from Outlook contact.

**Comment by peombwa** [comment] 2019-06-26 21:41
This is a duplicate of https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/198 and it's being tracked in our [backlog](https://github.com/microsoftgraph/msgraph-sdk-dotnet/projects/3). At the moment, all properties in a model are null when deserialized and the SDK doesn't do a null serialization of them.

**Closed** 2019-06-27 22:00 UTC
Labels: duplicate
