### ISSUE TITLE
Request retry failed with empty body

### ISSUE THREAD

**Issue by kyzhangZao** [microsoftgraph/msgraph-sdk-dotnet#2510] opened 2024-05-22 14:28 UTC
### Describe the bug

Hi SDK team,

Our service is on sdk version 5.31.0, and this is the latest capable version with our framework.
An unexpected behavior we started to get after switch to use this sdk version (from sdk version 3.19) is that retries handled by Polly ExecuteAsync is sending empty request body/some of the request properties are missing, which lead to the retry failure. The request body contains all expected properties during the first attempt. Issues are only seen in retries.

### Expected behavior

Object created outside of the retry block should be picked up correctly by the Polly handler.

### How to reproduce

code snippet
```
var secret = 'some secret';
var subscription = new Subscription {
    Resource = $"{Some resource name}",
    ClientState = secret.ToString(),
    ExpirationDateTime = DateTime.UtcNow.AddHours(some time interval)
};
var createdSubscription = await retryPolicy.ExecuteAsync(
    context => graphServiceClient.Subscriptions.PostAsync(subscription),
    traceableData.AsPollyContext()).ConfigureAwait(false);
```

### SDK Version

5.31.0

### Known Workarounds

Our workaround at this moment is to recreate the object within the retry block with all the required properties. But we would like to understand the reason why the object is not being picked up correctly if it's being created outside of the retry block.

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

### Other information

We're a 1p app, feel free to reach out on Teams

**Comment by andrueastman** [comment] 2024-05-23 06:53
Thanks for raising this @kyzhangZao 

I believe this is caused by the functionality of the backing store that keeps track of data that is serialized out. 
https://learn.microsoft.com/en-us/openapi/kiota/backing-store. 

To resolve this, you would probably need to recreate the object within the retry block. Or add this line in the block before sending out the retry.
`subscription.BackingStore.IntitializationCompleted = false; `

Out of curiosity, is there a specific reason that you do not use the inbuilt retry mechanism available in the SDK?
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#per-request-options

**Comment by kyzhangZao** [comment] 2024-05-23 23:49
Hi @andrueastman ,

Thanks for the above info.

Regarding to retry,
The retry mechanism predates the use of the SDK (some historical reason) and we retry on specific error messages. And our retry mechanisms applies to all the requests from the graphclient, we don't have use cases that we set special rules for specific requests.

**Comment by andrueastman** [comment] 2024-05-29 07:00
Thanks for the extra info @kyzhangZao 

We'll close this one for now.  Feel free to re-open/create new issue incase of anything else.

**Closed by andrueastman** 2024-05-29 07:00 UTC
Labels: Needs: Attention :wave:, status:waiting-for-author-feedback, type:bug, type:question
