### ISSUE TITLE
GraphServiceClient.Users.GetAsync() is not respecting QueryParameters.Select

### ISSUE THREAD

**Issue by drewid** [microsoftgraph/msgraph-sdk-dotnet#2304] opened 2024-01-25 21:47 UTC
**Describe the bug**
No matter what **QueryParameters.Select** fields are entered, the Users.GetAsync() and Users["user"].GetAsyc() query returns all the fields for a user instead of the subset.  My code is close to identical to MS standard examples.

**To Reproduce**

**IDE Setup**
Visual Studio 17.8.3
.NET 8.0 C# command line project

**Steps**
1. Created a GraphClient _graphClient (_success_)
2. Added values to a user for ExtensionAttribute1 and ExtensionAttribute2 (_success_)
3. Added Directory Extension (_success_)

4a. Return the fields Id, DisplayName, OnPremisesExtensionAttributes (_**failure**_)
4b. Return the fields Id, DisplayName, extension_clientid_extensionname (_**failure**_)
4c. Return just the fields Id and DisplayName (_**failure**_)

**Problem**
No matter what is put in the values for **QueryParameters.Select** all the fields are returned for the user instead of the subset specified in the Select array.

I have tried changing the case of the fields (Camel Case vs Capitalized) to no luck.

**Expected behavior**
Only the fields that were specified during the select should be returned.

**Code**

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/375184/49b74743-3139-4399-a726-67e80b983766)

`
var result = await _graphClient.Users["userid"].GetAsync((requestConfiguration) =>
{
    requestConfiguration.QueryParameters.Select = new[] { "Id", "DisplayName", "OnPremisesExtensionAttributes" };
});
return result;
`

The response returns the full list of user fields.  Example snippet:

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/375184/370589d9-cffd-442b-9656-7aaeb6d80dca)

**Comment by andrueastman** [comment] 2024-01-26 06:34
Thanks for raising this @drewid 

Any chance you can confirm the method you are verifying the properties returned from `result` object? If you are serializing the object the object, are you using this?

```cs
var jsonString = var jsonString = KiotaJsonSerializer.SerializeAsString(result);
```

**Comment by drewid** [comment] 2024-01-27 05:18
I printed out the serialized results using the following:
`    Console.WriteLine(JsonConvert.SerializeObject(result));`

I would not expect to see all of the fields having been returned.

When I used the following you mentioned, it is empty
`var jsonString = KiotaJsonSerializer.SerializeAsString(result);`

**Comment by andrueastman** [comment] 2024-01-29 07:11
Thanks for getting back @drewid 
Any chance this shows the values returned? Due to the [backingStore](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#backing-store), the properties may not show as the serializer will pick out only changed values after the response. 
```cs
result.BackingStore.InitializationCompleted = false;
var jsonString = KiotaJsonSerializer.SerializeAsString(result);
```

**Comment by drewid** [comment] 2024-01-29 08:12
A get should never just return changed values and that is not implied anywhere in the docs.

**Comment by drewid** [comment] 2024-01-29 08:14
I will dig further but this is a royal mess.

- A default query should return all values.
- A select should return just those mentioned and not the slew being returned

**Comment by drewid** [comment] 2024-01-29 20:50
@andrueastman Thank you for the magical code snippet regarding the BackingStore - I have no idea why that magically makes things work in making the serialization honor the select list (or at least properly trim the fields).

What is misleading though is that **the query still returns "every" field**, including the selected fields requested.  The KiotaJsonSerializer is being applied after the fact and I can see the query is returning all the fields when doing a basic serialization of the result.  This is remarkably misleading and incredibly wasteful.  What has been implemented is not a select parameter, it's actually a "make sure to include these fields" parameter.

The information related to KiotaJsonSerializer and v5 breaking change regarding BackingStore needs a "lot" more information publicly.  Is not listed anywhere in the normal docs and examples that I can see.

In essence, the standard described ways of doing QueryParameters.Select do not work without it (at least narrowing it down).  It does include the fields selected, but also includes every other field.

**Comment by andrueastman** [comment] 2024-01-30 10:23
Thanks for the feedback here @drewid 

Just to clarify, what is indeed happening is that API is indeed only returns the fields selected(This can be confirmed using the [Graph Explorer](https://aka.ms/ge) ). 
However, the model properties will by default read as null by a serializer if they have not been set due to the proxy mechanism used by the backing store. The `KiotaJsonSerializer` is built for this and can be used to get back the Json received or to be sent out by a given execution call. 

This indeed should be better documented, and we've created https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2310 to update the v5 documentation here.

**Comment by drewid** [comment] 2024-02-06 00:04
Better documentation will be great because it is 100% not intuitive and not at all clear.

**Comment by andrueastman** [comment] 2024-02-09 13:06
Thanks for the feedback here @drewid. We'll close this for now and track this via https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2310

**Closed by andrueastman** 2024-02-09 13:06 UTC
Labels: Question: SDK, Needs: Attention :wave:
