### ISSUE TITLE
Skiptoken queryparameter support (SDK V5)

### ISSUE THREAD

**Issue by CeesJanNolen** [microsoftgraph/msgraph-sdk-dotnet#1792] opened 2023-03-30 12:52 UTC
We're using the C# Graph SDK in our application. 
Before we're using the API, but we wanted to move to the native c# SDK for direct support of models and so on.

In the SDK (v5+) we've noticed that the query parameter support for the skiptoken has been dropped.
The API uses:
`"@odata.nextLink": "https://graph.microsoft.com/v1.0/users?$top=5&$skiptoken=X%274453707 ... 6633B900000000000000000000%27"`

The updated SDK (v5) now uses the requestConfiguration.
`This one only supports items like Select, Count, Search, Filter.`

We know there is an option to use the PageIterator, but we cannot use that one in our application. This is because we're using (among other things) a table view in which we use the nextpagelink for retrieving the next page. Therefore we are looking for that skiptoken option, which is the only way so far for our application to use the SDK.

We guess this should still be possible, but we're not sure how to approach that.

Our ideal solution might look something like:
`GetUsers(string? skiptoken) --> Call users.getAsync(//request parameters in here). `
Based on the skiptoken being present, we would like to add the skiptoken to the request queryparameters and use it to skip to the specific page.

**Comment by idealser** [comment] 2023-03-30 14:59
Hi @CeesJanNolen! Check [#1689](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1689#issuecomment-1467738178). This is the only way to set it for now, until it's fixed.

**Comment by andrueastman** [comment] 2023-03-30 15:06
Thanks for raising this @CeesJanNolen 

We'll close this as this is a duplicate of https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1689 where the metadata needs to be fixed to expose the other parameters and a way around has been provided.

**Closed by andrueastman** 2023-03-30 15:06 UTC
Labels: Needs: Triage
