### ISSUE TITLE
New PlannerTask "parameter count mismatch" error

### ISSUE THREAD

**Issue by pbaumhart** [microsoftgraph/msgraph-sdk-dotnet#956] opened 2021-04-07 23:07 UTC
Microsoft.Graph v4.0.0-preview.2

When trying to add a PlannerTask with Assignments or Details, I receive a System.Reflection.TargetParameterCountException when making the request.

It works if the Assignments and Details are omitted.

v3.29 works as expected

### Expected behavior

A task is added to the specified planner bucket with Details and Assignments

### Actual behavior

System.Reflection.TargetParameterCountException

### Steps to reproduce the behavior
```
var app = PublicClientApplicationBuilder
                    .Create("ClientId")
                    .WithAuthority($"https://login.microsoftonline.com/{Tenant Id}")
                    .Build();

var scopes = new string[] { "User.Read", "Group.ReadWrite.All" };
var authProvider = new IntegratedWindowsAuthenticationProvider(app, scopes);
var gclient = new GraphServiceClient(authProvider);

var assignments = new PlannerAssignments();
assignments.AddAssignee("A user id");

var details = new PlannerTaskDetails
{
    Description = "Test Description"
};

var task = new PlannerTask
{
    PlanId = "A Plan Id",
    BucketId = "A Bucket Id",
    Title = "Test Title",
    Assignments = assignments,
    Details = details
};

var resp = await gclient.Planner.Tasks.Request().AddAsync(task); 
//Exception occurs here, i'm guessing during deserialization of task
```

If this is run with v4.0.0-preview.2, i receive the System.Reflection.TargetParameterCountException.
If this is run with v3.29, it works as expected
If I comment out the Assignments and Details assignments, it also works as expected even in v4.0.0-preview.2

Full package list for test application:

- Microsoft.Extensions.Configuration.Json v6.0.0-preview.2.21154.6
- Microsoft.Graph v4.0.0-preview.2
- Microsoft.Graph.Auth v1.0.0-preview.6
- Microsoft.Identity.Client v4.29.0
- System.Net.Http.Json v6.0.0-preview.2.21154.6

Thanks for looking at this!
 
[AB#8892](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8892)

**Comment by andrueastman** [comment] 2021-04-08 10:44
Thanks for raising this issue @pbaumhart. And for trying out the preview!
It looks like the error is caused by the serializer trying to serialize some public properties added through the extensions [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/d3fceeedf05243f9c5b90d0f15c1a12606a3494b/src/Microsoft.Graph/Models/Extensions/PlannerAssignments.cs#L43).
This will be resolved by adding the relevant attributes to ignore the properties during serialization/deserialization.

**Comment by andrueastman** [comment] 2021-04-22 09:12
This should now be resolved in Microsoft.Graph 4.0.0-preview.3

**Closed by andrueastman** 2021-04-22 09:12 UTC
Labels: Bug, under investigation

**Comment by pbaumhart** [comment] 2021-04-22 18:29
Thank you! (hopefully) quick question for you. I'm having another issue tangentially related to this, but not sure where to put it. When I make the post to add a task, if it has assignments or checklist items, i'm getting a response from the api of "A type named 'microsoft.taskServices.plannerAssignmentCollection' could not be resolved by the model." (type is different for checklist items, but same error). I'm pretty sure this was working before last week. When I serialize the task using the graph client HttpProvider.Serializer and paste it into graph explorer i get the same error. If i remove the "@odata.type": "microsoft.graph.plannerAssignments" property from the assignments object (and the corresponding checklist items type property), it works. This is happening in latest stable and now preview 3.  Would i post that issue in this repo? Not sure if the problem is with the serialization or if something changed in the endpoint, or maybe I'm doing something wrong? Thanks!

**Comment by andrueastman** [comment] 2021-04-23 06:33
Hey @pbaumhart.
That is a known issue related to some workloads which do not like the setting of the "@odata.type". This is related to https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/226.
We are currently advising sdk users to workaround this by doing something like code snippet below as we investigate having the sdk code generator to identify such models and set the OdataType to null by default.

```cs
var todoTaskList = new TodoTaskList
{
        ODataType = null, // unset this value
	DisplayName = "Travel items"
};
```

**Comment by pbaumhart** [comment] 2021-04-23 14:13
@andrueastman, Thank you very much!
