### ISSUE TITLE
Newtonsoft.Json.JsonReaderException on Reports endpoints

### ISSUE THREAD

**Issue by wadstromdev** [microsoftgraph/msgraph-sdk-dotnet#551] opened 2019-10-04 09:50 UTC
Please provide the following (and please check them off the list with [x]) before submitting this issue:
- [X] Expected behavior. Please provide **links to the specific [Microsoft Graph documentation](https://developer.microsoft.com/en-us/graph/docs/concepts/overview)** you used to determine the expected behavior. 
- [X] Actual behavior. Provide error codes, stack information, and a [Fiddler](http://www.telerik.com/fiddler) capture of the request and response (please remove personally identifiable information before posting).
- [X] Steps to reproduce the behavior. Include your code, IDE versions, client library versions, and any other information that might be helpful to understand your scenario.

### Expected behavior
https://docs.microsoft.com/en-us/graph/api/reportroot-getteamsdeviceusageuserdetail?view=graph-rest-1.0&tabs=csharp#tabpanel_CeZOj-G++Q_csharp
Should return a Report object when calling for example
```
GraphServiceClient graphClient = new GraphServiceClient( authProvider );
DateTime reportDate = DateTime.Today.AddDays(-5);
Date date = new Date(reportDate.Year, reportDate.Month, reportDate.Day);
Report report = await graphClient.Reports.GetTeamsDeviceUsageUserDetail(date).Request().GetAsync();
```

### Actual behavior
Throws a Newtonsoft.Json.JsonReaderException, see code example above.
![image](https://user-images.githubusercontent.com/36885853/66198063-ebafd800-e69b-11e9-8ed3-c8410e212a10.png)

Framework: .net core 2.1
Microsoft.Graph version: 1.17.0
Microsoft.Graph.Core version: 1.17.0
Newtonsoft.Json version: 11.0.2

### Steps to reproduce the behavior
See example code in Expected behavior

**Comment by MIchaelMainer** [comment] 2019-10-04 17:17
This is duplicate of https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/534. There is a workaround described in the linked issue.

**Closed by MIchaelMainer** 2019-10-04 17:17 UTC
Labels: duplicate
