### ISSUE TITLE
Move to parameter objects in C# 

### ISSUE THREAD

**Issue by fey101** [microsoftgraph/msgraph-sdk-dotnet#1202] opened 2021-12-17 22:16 UTC
Order of parameters is not guaranteed in such a request as this: (Example extracted from documentation page [here](https://docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-beta&tabs=csharp#http-request-1))
```C#
GraphServiceClient graphClient = new GraphServiceClient( authProvider );

var recipients = new List<DriveRecipient>()
{
	new DriveRecipient
	{
		Email = "robin@contoso.org"
	}
};

var message = "Here's the file that we're collaborating on.";

var requireSignIn = true;

var sendInvitation = true;

var roles = new List<String>()
{
	"write"
};

var password = "password123";

var expirationDateTime = "2018-07-15T14:00:00Z";

await graphClient.Me.Drive.Items["{driveItem-id}"]
	.Invite(recipients,requireSignIn,roles,sendInvitation,message,expirationDateTime,password)
	.Request()
	.PostAsync();
```

Moving to parameter objects will eliminate the need for rigid parameter ordering 
More on this discussed on this PR https://github.com/microsoftgraph/msgraph-metadata/pull/64

**Comment by zengin** [comment] 2021-12-17 22:23
@andrueastman is there a duplicate of this issue being tracked for the next version of the .NET SDK?

**Comment by andrueastman** [comment] 2021-12-20 05:44
@zengin, The Kiota generator of the SDK already supports this.

**Comment by andrueastman** [comment] 2022-05-20 13:06
Closing this for now.

With the Kiota based previews you should be able to do something like using the generated parameter objects.

```cs
  var invitePostBody = new InvitePostRequestBody
  {
      Recipients = new List<DriveRecipient>
      {
          new DriveRecipient
          {
              Email = "robin@contoso.org"
          }
      },
      Message = "Welcome",
      RequireSignIn = false,
      SendInvitation = true,
      Roles = new List<string>
      {
          "write"
      }
  };
  
  await graphServiceClient.Workbooks["workbook-itemId"]
      .Invite
      .PostAsync(invitePostBody);
```

**Closed by andrueastman** 2022-05-20 13:06 UTC
Labels: Kiota
