### ISSUE TITLE
Unable to append OData type in Request URL

### ISSUE THREAD

**Issue by kalyankrishna1** [microsoftgraph/msgraph-sdk-dotnet#1177] opened 2021-11-23 21:53 UTC
**Is your feature request related to a problem? Please describe.**
I am trying to wrap the following call in the Graph SDK

`https://graph.microsoft.com/V1.0/me/memberOf/microsoft.graph.group`

The code that I have in hand is the following

`var mymemberships = await graphServiceClient.Me.MemberOf.Request().GetAsync();`

The issue is that the CSharp code above creates a request url in the following form, thus offloading the task of filtering the groups and directory roles in my code..

`https://graph.microsoft.com/V1.0/me/memberOf/`

**Describe the solution you'd like**

Ideally, the request builder should have a mechanism that allows OData type (that's what I think `microsoft.graph.group` is) appended to the request

**Describe alternatives you've considered**

I am forced to filter the various types of memberships (groups and directory roles) in my code

**Additional context**
I scanned through the example in [docs](https://docs.microsoft.com/en-us/graph/sdks/create-requests?tabs=CS)and elsewhere, but see no way of getting the URL in the form I desire.

**Comment by andrueastman** [comment] 2021-11-24 06:43
Hey @kalyankrishna1, 

Thanks for raising this issue.

This is caused by the SDK generator not supporting TypeSegments in the URL and you should be able to work around this by 

```cs
var graphClient = new GraphServiceClient(interactiveBrowserCredential, scopes);
var requestUrl = graphClient.Me.MemberOf.AppendSegmentToRequestUrl("microsoft.graph.group");
var groups = await new GraphServiceGroupsCollectionRequestBuilder(requestUrl, graphClient).Request().GetAsync();
```

We are tracking this https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/issues/239 and wil close this for now for it to be tracked there.

**Closed by andrueastman** 2021-11-24 06:43 UTC
Labels: ToTriage
