### ISSUE TITLE
Wrong C# code snippets for Directory Role APIs - List members

### ISSUE THREAD

**Issue by FaithOmbongi** [microsoftgraph/msgraph-sdk-dotnet#1043] opened 2021-06-18 15:38 UTC
Hello,

I raised a PR to update an example & request new code snippets for the [directoryRole: List members](https://docs.microsoft.com/en-us/graph/api/directoryrole-list-members?view=graph-rest-beta) API. However, the C# code snippets where the request uses the **roleTemplateId** instead of directoryRole **id** are incorrect.

**Current snippet**
From [List members: Example 2 (v1.0)](https://docs.microsoft.com/en-us/graph/api/directoryrole-list-members?view=graph-rest-1.0&tabs=csharp#example-2-get-the-members-of-a-directory-role-using-role-templateid), [Example 2 (beta)](https://docs.microsoft.com/en-us/graph/api/directoryrole-list-members?view=graph-rest-beta&tabs=csharp#example-2-get-the-members-of-a-directory-role-using-role-templateid)
```C#
GraphServiceClient graphClient = new GraphServiceClient( authProvider );

var members = await graphClient.DirectoryRoles["{directoryRole-id}"].Members
	.Request()
	.GetAsync();
```

**Expected behavior** (as extracted from Graph Explorer)
```c#
GraphServiceClient graphClient = new GraphServiceClient( authProvider );

var members = await graphClient.DirectoryRoles["roleTemplateId=4a5d8f65-41da-4de4-8968-e035b65339cf"].Members
	.Request()
	.GetAsync();
```

**Additional context**
- Related issues: #1041 , #1042 
- PR to request new code snippets: https://github.com/microsoftgraph/microsoft-graph-docs/pull/13026
- Affects only C#.
 
[AB#9958](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9958)

**Comment by andrueastman** [comment] 2021-06-29 14:37
This seems to be the intended behavior to enable testing and validation of the snippets as the snippets in the docs need to have placeholder values to enable execution tests to ensure their correctness. See [here](https://github.com/microsoftgraph/microsoft-graph-devx-api/blob/dev/CodeSnippetsReflection/LanguageGenerators/CSharpGenerator.cs#L341)

Graph Explorer users will not see this behavior and this change is expected to propagate to other languages as the snippet validation is implemented in those languages as well. 

Closing this for now.

**Closed by andrueastman** 2021-06-29 14:37 UTC
