### ISSUE TITLE
Authentication Always null

### ISSUE THREAD

**Issue by exuviae** [microsoftgraph/msgraph-sdk-dotnet#857] opened 2020-12-07 23:00 UTC
I load a user with the following code:

 var locatedUser = graphClient.Users.Request()
                .Filter($"otherMails/any(id:id eq '{emailAddress}') or userPrincipalName eq '{emailAddress}' or mail eq '{emailAddress}'")
                .GetAsync()
                .Result;

when looking at locatedUser[0].Authentication it is always null.  I can load with Query or with Id, and the result is the same.  Is there something i am missing related to getting the authentication methods?

**Comment by pschaeflein** [comment] 2020-12-08 04:58
Which property of the User are you looking for? I don't see "Authentication" on the [documentation page](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0#properties)

**Comment by exuviae** [comment] 2020-12-08 13:30
I am looking for the phoneMethods.  We manage a b2c instance and have many users that either changed phones and can’t login, or the uninstalled authenticator and can’t log in.  Off of User, there is an object called Authentication that has phoneMethods as a property.
Chris


Sent from Yahoo Mail for iPhone


On Monday, December 7, 2020, 10:58 PM, Paul Schaeflein <notifications@github.com> wrote:




Which property of the User are you looking for? I don't see "Authentication" on the documentation page

**Comment by exuviae** [comment] 2020-12-08 14:04
Slightly more complete sample. 

IConfidentialClientApplication confidentialClientApplication = ConfidentialClientApplicationBuilder
	.Create(clientId)
	.WithTenantId(tenantId)
	.WithClientSecret(clientSecret)
	.Build();

ClientCredentialProvider authProvider = new ClientCredentialProvider(confidentialClientApplication);
GraphServiceClient graphClient = new GraphServiceClient(authProvider);

var locatedUser = graphClient.Users.Request()
	.Filter($"otherMails/any(id:id eq '{emailAddress}') or userPrincipalName eq '{emailAddress}' or mail eq '{emailAddress}'")
	.GetAsync()
	.Result;
foreach (var user in locatedUser)
{
	if (user.Authentication != null)
	{
		foreach (var authenticationPhoneMethod in user.Authentication.PhoneMethods)
		{
			Console.WriteLine(authenticationPhoneMethod.PhoneNumber);
		}
	}
	else
		Console.WriteLine("Authentication methods does not exist");
}

**Comment by MIchaelMainer** [comment] 2020-12-10 21:12
This is a duplicate of https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/199

**Closed by MIchaelMainer** 2020-12-10 21:12 UTC
Labels: ToTriage
