### ISSUE TITLE
[Client bug]: PATCH Planner.Tasks[id].Details ChecklistItems Odata Type not serializing correctly.

### ISSUE THREAD

**Issue by WadeTheFade** [microsoftgraph/msgraph-sdk-dotnet#1933] opened 2023-05-25 21:26 UTC
**Describe the bug**
When updating a planner task, it fails with the following error:
```
The request is invalid:
Value cannot be null.
Parameter name: qualifiedName
```

**To Reproduce**
This is very similar to #1729 . All steps to reproduce can be done the exact same way except with Checklist in PlannerTaskDetails.

The simplest representation of my code is:
```
var plannerTaskDetails = await _graphServiceClient.Planner.Tasks[task.Id].Details.GetAsync();
plannerTaskDetails.Checklist.AdditionalData = checklistItems; //Dictionary<string,object>();
await _graphServiceClient.Planner.Tasks[task.Id].Details.PatchAsync(plannerTaskDetails);
```

I was not able to implement the workaround listed for this as I was updating an existing planner by adding a checklist to it. In trying to work around many other properties not serializing correctly with the same behavior (`Checklist` for one)
I copy/pasted the example from the [documentation on PlannerTaskDetails](https://learn.microsoft.com/en-us/graph/api/plannertaskdetails-update?view=graph-rest-1.0&tabs=csharp) and it still failed to Patch. 

**Expected behavior**
The `OdataType` should be serialized to `@odata.type`.
The `OrderHint` should be serialized to `orderHint`.
The `IsChecked` should be serialized to `isChecked`.

**Client version**
5.11.0

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
This is some of the modeling I was doing to get around the Bad Request errors during attempting the work around:

```
   public class CheckListItem
    {
        [JsonPropertyName("displayName")]
        public string DisplayName { get; set; }
        [JsonPropertyName("orderHint")]
        public string OrderHint { get; set; } = " !";
        [JsonPropertyName("@odata.type")]
        public string OdataType { get; set; }
        [JsonPropertyName("isChecked")]
        public bool IsChecked { get; set; } = false;
    }
    public class PlannerTaskDetails
    {
        [JsonPropertyName("checklist")]
        public PlannerChecklistItems Checklist { get; set; }
        [JsonPropertyName("previewType")]
        public string PreviewType { get; set; }
    }
    public class PlannerChecklistItems
    {
        public Dictionary<string, object> AdditionalData { get; set; }
        
    }
 ```

**Comment by mmamfgm** [comment] 2023-07-17 19:35
I have the same issue, hope this will be fixed soon. For now, we will stick with the v4 Graph SDK. @andrueastman the same problem is happening with PlannerExternalReferences.

**Comment by andrueastman** [comment] 2023-08-24 07:23
Closing as duplicate of https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2050. Resolved with https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/2095

**Closed by andrueastman** 2023-08-24 07:23 UTC
Labels: Bug, Bug: documentation
