### ISSUE TITLE
[Client bug]: `TableRowCollection: add` is broken in v5?

### ISSUE THREAD

**Issue by nickwb** [microsoftgraph/msgraph-sdk-dotnet#1928] opened 2023-05-25 03:53 UTC
**Describe the bug**
It's not clear that it is possible to construct a valid instance of `Microsoft.Graph.Drives.Item.Items.Item.Workbook.Worksheets.Item.Tables.Item.Rows.Add.AddPostRequestBody`.

This HTTP request requires a property "values", that contains nested JSON, which expects "an array of arrays", where each inner array is a complete row to be inserted to the table.

However, it is not clear at all how to construct an instance of the `Microsoft.Graph.Models.Json` type that is for the `AddPostRequestBody.Values` property.

The C# code example that is provided on [this Microsoft documentation page](https://learn.microsoft.com/en-us/graph/api/tablerowcollection-add?view=graph-rest-1.0&tabs=csharp) is clearly nonsense.

**Expected behavior**
`TableRowCollection: add` should be supported in v5 (it works fine in v4).

**Screenshots**

**Client version**
5.11.0

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by MartinM85** [comment] 2023-05-25 09:53
Working with workbook is still not supported in v5. This is another issue.

**Comment by JoseCarreira2018** [comment] 2023-05-28 18:55
i am trying to figure out how write new rows, with this [https://learn.microsoft.com/en-us/graph/api/tablerowcollection-add?view=graph-rest-1.0&tabs=csharp](url) but i have  a error with the format of the data. The example from mirosoft is confused for me . If in previus version worked can someone share the a example of working code and the exact version
Thank´s

**Comment by nickwb** [comment] 2023-05-29 06:07
@JoseCarreira2018 - in the v4 SDK, you can try this:

```csharp
var myDriveId = "xxx";
var myWorkbookPath = "some_folder/workbook.xlsx"
var myTableName = "MyTable"

var table = _graphClient.Drives[myDriveId].Root.ItemWithPath(myWorkbookPath).Workbook.Tables[myTableName];

// In this example: Two rows to insert, each with three columns
var rowsToAdd = JsonDocument.Parse("[[1,2,3][4,5,6]]");

// If you need to build this dynamically, you might find JsonArray in System.Text.Json.Nodes to be helpful

var response = await table.Rows.Add(values: rowsToAdd).Request().PostAsync(CancellationToken.None);
// If this needs to run frequently, you should probably pass a session Id when calling "Request"
// See: CreationSession on the workbook.
// You can pass as: new HeaderOption("Workbook-Session-Id", mySessionId)

```

This is a very simplified version of code I had working correctly against `4.48.0` of `Microsoft.Graph` - though I suspect it will work fine with any v4 version.

**Comment by JoseCarreira2018** [comment] 2023-06-05 09:59
@nickwb Thank´s for the help but i need it work on v5.12

in sample code from microsoft the problem is the format of the data was i want insert. There is another way to load the "Values"/Data to insert?


// Code snippets are only available for the latest version. Current version is 5.x

var graphClient = new GraphServiceClient(requestAdapter);

var requestBody = new Microsoft.Graph.Drives.Item.Items.Item.Workbook.Tables.Item.Rows.Add.AddPostRequestBody
{
	Index = 5,
	Values = new List<List<1>>
	{
		new List<1>
		{
			1,
			2,
			3,
		},
		new List<4>
		{
			4,
			5,
			6,
		},
	},
};
var result = await graphClient.Drives["{drive-id}"].Items["{driveItem-id}"].Workbook.Tables["{workbookTable-id}"].Rows.Add.PostAsync(requestBody);

**Comment by nickwb** [comment] 2023-06-05 11:19
@JoseCarreira2018 - It doesn't work on 5.x, that's why I raised this as a bug.

Yes, I've seen that code example too. It doesn't work. It's very clearly a broken example. It's not even syntactically valid C#, let alone something that will pass a type check.

The only way to do it in 5.x is to call `_graphClient.RequestAdapter.SendAsync` directly.

**Comment by werwolfby** [comment] 2023-06-16 16:07
I've added corresponding issue to the docs: https://github.com/microsoftgraph/microsoft-graph-docs/issues/21677
Because example is non-sense.

And the whole `Json` API is dumb. Why it can be only object instead of just literals and arrays. But for some reason it allows to track changes?

How this was created at all? It doesn't do required things, like convert C# structs/classes to JSON, but allow to track changes...

**Comment by werwolfby** [comment] 2023-06-16 16:09
v4 example like this:
```c#
var rowsToAdd = JsonDocument.Parse("[[1,2,3][4,5,6]]");
```

Was stupid too, I have a C# class, that then I have to convert it to JSON string, to parse it back into `JsonDocument`, to parse it to JSON during sending request. WTF???? Some steps are clearly not needed.

I can create JSON document directly, but why this is not automated.

So this package is not a high-level API is some dumb wrapper 😢.

**Comment by MartinM85** [comment] 2023-06-16 19:25
@andrueastman Is there any ETA when SDK v5 will support workbook endpoints?

**Comment by JoseCarreira2018** [comment] 2023-06-30 16:36
A workaround using client.SendAsync that work´s:
`    public async static  Task AddInfoToExcel(string accessToken, string name, string address)
    {
        string endpoint = "https://graph.microsoft.com/v1.0/users/carreira@acatel.pt/drive/items/01M45CPBPFYESLZSCWVFDI42ZKKPWQNNPD/workbook/tables/Tabela1/rows/add";
        using (var client = new HttpClient())
        {
            using (var request = new HttpRequestMessage(HttpMethod.Post, endpoint))
            {
                // Populate UserInfoRequest object
                string[] userInfo = { name, address };
                string[][] userInfoArray = { userInfo };
                UserInfoRequest userInfoRequest = new UserInfoRequest();
                userInfoRequest.index = null;
                userInfoRequest.values = userInfoArray;

              

                // Serialize the information in the UserInfoRequest object
                string jsonBody = JsonConvert.SerializeObject(userInfoRequest);
                request.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
                request.Content = new StringContent(jsonBody, Encoding.UTF8, "application/json");

                using (var response = await client.SendAsync(request))
                {
                    if (response.IsSuccessStatusCode)
                    {
                        return Resource.Graph_UploadToExcel_Success_Result;
                    }
                    return response.ReasonPhrase;
                }
            }
        }
    }`

**Comment by JoseCarreira2018** [comment] 2023-06-30 16:38
A workaround that work´s using sendasync :
`
    public async static  Task AddInfoToExcel(string accessToken, string name, string address)
    {
        string endpoint = "https://graph.microsoft.com/v1.0/users/carreira@acatel.pt/drive/items/01M45CPBPFYESLZSCWVFDI42ZKKPWQNNPD/workbook/tables/Tabela1/rows/add";
        using (var client = new HttpClient())
        {
            using (var request = new HttpRequestMessage(HttpMethod.Post, endpoint))
            {
                // Populate UserInfoRequest object
                string[] userInfo = { name, address };
                string[][] userInfoArray = { userInfo };
                UserInfoRequest userInfoRequest = new UserInfoRequest();
                userInfoRequest.index = null;
                userInfoRequest.values = userInfoArray;

              

                // Serialize the information in the UserInfoRequest object
                string jsonBody = JsonConvert.SerializeObject(userInfoRequest);
                request.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
                request.Content = new StringContent(jsonBody, Encoding.UTF8, "application/json");

                using (var response = await client.SendAsync(request))
                {
                    if (response.IsSuccessStatusCode)
                    {
                        return Resource.Graph_UploadToExcel_Success_Result;
                    }
                    return response.ReasonPhrase;
                }
            }
        }
    }

`

**Comment by craig-blowfield** [comment] 2024-05-10 12:52
I have only just started using the MS graph API and the dotnet SDK and I am amazed the state it is in and this is evidenced by the amount of raised issue around V5. Very poor quality control from MS and response.

Anyway I did get this working by creating my own body request for the request

``` cs
public class AddRowPostRequestBody : AddPostRequestBody
{
    public List<UntypedArray>? Rows
    {
        get { return BackingStore?.Get<List<UntypedArray?>?>("values"); }
        set { BackingStore?.Set("values", value); }
    }

    new public static AddRowPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
    {
        _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
        return new AddRowPostRequestBody();
    }

    public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
    {
        return new Dictionary<string, Action<IParseNode>>();
    }

    public override void Serialize(ISerializationWriter writer)
    {
        _ = writer ?? throw new ArgumentNullException(nameof(writer));

        writer.WriteIntValue("index", Index);

        writer.WriteCollectionOfObjectValues<UntypedArray>("values", Rows);
        writer.WriteAdditionalData(AdditionalData);
    }
}
```

Then you can a call like this

``` cs
private static async Task ExcelAddRow(GraphServiceClient? graphClient, DriveItem excelFolderDriveItem, string tableName, string[][] items)
{
    var rows = items.Select(i => new UntypedArray(i.Select(v => new UntypedString(v)))).ToList();

    var excelAddRowResponse = await graphClient.Drives[excelFolderDriveItem.ParentReference.DriveId].Items[excelFolderDriveItem.Id].Workbook.Tables[tableName].Rows.Add.PostAsync(new AddRowPostRequestBody
    {
        Rows = rows
    });
}
```

I am sure there is a better way to workaround the SDK being broke, but it worked!!!

Please MS, sort your SDK's out and maybe write some regression tests to prevent things becoming broke

**Comment by MartinM85** [comment] 2024-06-11 12:38
Should be fixed in the latest version

- Add table:
```
var table = await graphClient.Drives[{drive_id}].Items[{drive_item_id}].Workbook.Tables.Add.PostAsync(new AddPostRequestBody
{
    Address = "A1:B5",
    HasHeaders = true,
});
```

- Add rows to table:
```
 await graphClient.Drives[{drive_id}].Items[{drive_item_id}].Workbook.Tables[table.id].Rows.PostAsync(new WorkbookTableRow
{
    // 3 rows, 2 columns
    Values = new UntypedArray(new List<UntypedArray>
    {
        new UntypedArray(new List<UntypedNode>
        {
            new UntypedBoolean(true),
            new UntypedDecimal(25m)
        }),
        new UntypedArray(new List<UntypedNode>
        {
            new UntypedString("text"),
            new UntypedDouble(0.1)
        }),
        new UntypedArray(new List<UntypedNode>
        {
            new UntypedInteger(1),
            new UntypedFloat(65f)
        })
    })
});
```

**Comment by andrueastman** [comment] 2024-06-13 13:41
Closing this as this is now supported in the latest SDK version.

**Closed by andrueastman** 2024-06-13 13:41 UTC
Labels: Bug, Status: Needs investigation
