### ISSUE TITLE
[Client bug]: Authentication EmailMethods patch request bug v5

### ISSUE THREAD

**Issue by edwinvandriel** [microsoftgraph/msgraph-sdk-dotnet#1901] opened 2023-05-15 12:07 UTC
When calling te graph to change the email address for an EmailMethod I get a serializer exception "Unable to parse request body as an authentication method". I'm using the latest v5.10 sdk version.

Consider this sdk call:

            await _microsoftGraphClient
                        .Users[identifier]
                        .Authentication
                        .EmailMethods[authenticationMethodId]
                        .PatchAsync(new Microsoft.Graph.Beta.Models.EmailAuthenticationMethod {
                            EmailAddress = emailAddress
                        });

PATCH https://graph.microsoft.com/beta/users/<userId>/authentication/emailMethods/<emailMethodId>

When this request is send, the content is serialized by the SDK as:
{
 "@odata.type":"#microsoft.graph.emailAuthenticationMethod",
 "emailAddress":"myemailaddress@email.com"
}

The exception is generated because of the odata.type in the content. When I do the same call manual without the odata.type it succeeds.

Setting OdataType to null will not help because it still got serialized.

**Comment by andrueastman** [comment] 2023-05-17 13:35
Thanks for raising this @edwinvandriel 

We'll close this a duplicate of https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1616#issuecomment-1547530942 for now as we fix this.

**Closed by andrueastman** 2023-05-17 13:35 UTC
Labels: duplicate
