### ISSUE TITLE
BETA CLIENT - requestConfiguration.QueryParameters.Token = "latest"; Not Available

### ISSUE THREAD

**Issue by RickL1234** [microsoftgraph/msgraph-sdk-dotnet#2372] opened 2024-03-07 13:27 UTC
Using VS 2022 - 17.8.7
Microsoft Graph Beta Client - 5.65.0-preview

Microsoft Support has directed me to use the beta version of the API for my application.  I am attempting to use the Microsoft.Graph.Beta client to get listitem: delta.

Using Postman this GET returns the @odata.deltaLink when executed against the beta endpoint:

https://graph.microsoft.com/beta/sites/?????.sharepoint.com:/sites/????:/lists/<listid>/items/delta?token=latest

I am trying to use the C# example under Example 3: Delta Link Request in this BETA documentation: 

https://learn.microsoft.com/en-us/graph/api/listitem-delta?view=graph-rest-beta&tabs=csharp

This is the example:

var result = await graphClient.Sites["{site-id}"].Lists["{list-id}"].Items.Delta.GetAsDeltaGetResponseAsync((requestConfiguration) =>
{
	requestConfiguration.QueryParameters.Token = "latest";
});

However, .Token is not a method in the list of QueryParameters.  How to I get the delta token?

Let me know if you need any more info.

Thanks,
Rick L.

**Comment by andrueastman** [comment] 2024-03-18 06:43
Thanks for raising this @RickL1234 

This is currently caused by a metadata issue tracked via https://github.com/microsoftgraph/msgraph-metadata/issues/431. At the moment you can resolve this in the meantime using the suggestion in https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2277#issuecomment-1893160156

We'll close this for now so that this is tracked via https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2277

**Closed by andrueastman** 2024-03-18 06:43 UTC
