### ISSUE TITLE
Microsoft Teams CreateAync: No HTTP resource was found that matches the request URI 

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/msgraph-sdk-dotnet#361] opened 2019-01-16 23:11 UTC
Please provide the following (and please check them off the list with [x]) before submitting this issue:
- [x] Expected behavior. Please provide **links to the specific [Microsoft Graph documentation](https://docs.microsoft.com/en-us/graph/api/team-put-teams?view=graph-rest-1.0)**
- [x] Actual behavior. 
- [x] Steps to reproduce the behavior. Include your code, IDE versions, client library versions, and any other information that might be helpful to understand your scenario.

### Expected behavior
Enabling teams on an existing group to work properly with the following code.
```CS
await client.Groups[input.GroupId].Team.Request().CreateAsync(new Team
            {
                MemberSettings = new TeamMemberSettings
                {
                    AllowCreateUpdateChannels = true,
                },
                MessagingSettings = new TeamMessagingSettings
                {
                    AllowUserEditMessages = true,
                    AllowUserDeleteMessages = true,
                },
                FunSettings = new TeamFunSettings
                {
                    AllowGiphy = true,
                    GiphyContentRating = GiphyRatingType.Strict
                }
            });
```
Does not work
```CS
await client.Groups[input.GroupId].Team.Request().PutAsync(new Team
            {
                MemberSettings = new TeamMemberSettings
                {
                    AllowCreateUpdateChannels = true,
                },
                MessagingSettings = new TeamMessagingSettings
                {
                    AllowUserEditMessages = true,
                    AllowUserDeleteMessages = true,
                },
                FunSettings = new TeamFunSettings
                {
                    AllowGiphy = true,
                    GiphyContentRating = GiphyRatingType.Strict
                }
            });
```
Works

### Actual behavior
```
Executed 'EnableTeamActivity' (Failed, Id=4da0dba4-5b60-4895-901c-9c79a51b6283)
[2019-01-16 10:36:05 PM] System.Private.CoreLib: Exception while executing function: EnableTeamActivity. Microsoft.Graph.Core: Message: No HTTP resource was found that matches the request URI 'https://api.teams.skype.com/v1.0/groups('047a17d2-f77e-4e57-bcab-caa4b7ee244b')/team'.
[2019-01-16 10:36:05 PM]
[2019-01-16 10:36:05 PM] Inner error
[2019-01-16 10:36:05 PM] .
[2019-01-16 10:36:05 PM] 936c43d026a147f6b24298dfca213660: Function 'EnableTeamActivity (Activity)' failed with an error. Reason: Microsoft.Graph.ServiceException: Message: No HTTP resource was found that matches the request URI 'https://api.teams.skype.com/v1.0/groups('047a17d2-f77e-4e57-bcab-caa4b7ee244b')/team'.
[2019-01-16 10:36:05 PM]
[2019-01-16 10:36:05 PM] Inner error
[2019-01-16 10:36:05 PM]
[2019-01-16 10:36:05 PM]    at Microsoft.Graph.HttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
[2019-01-16 10:36:05 PM]    at Microsoft.Graph.BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
[2019-01-16 10:36:05 PM]    at Microsoft.Graph.BaseRequest.SendAsync[T](Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
[2019-01-16 10:36:05 PM]    at Microsoft.Graph.TeamRequest.CreateAsync(Team teamToCreate, CancellationToken cancellationToken)
```

### Steps to reproduce the behavior
- Create an Office 365 group (within outlook or SharePoint, no Teams enabled
- Implement the following code
- Exception thrown

**Comment by MIchaelMainer** [comment] 2019-01-16 23:40
Thank you Vincent. This is a duplicate of https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/341.

We don't have a way to discover that this is a PUT when we generate from the metadata. I added the PutAsync() to support this.

**Closed by MIchaelMainer** 2019-01-16 23:40 UTC
Labels: duplicate

**Comment by baywet** [comment] 2019-01-17 01:09
Thanks Micheal, sorry I didn't see this one when I was looking for existing issues
