### ISSUE TITLE
How to include photo with user search (filter)

### ISSUE THREAD

**Issue by rmmcgr** [microsoftgraph/msgraph-sdk-dotnet#1173] opened 2021-11-18 03:27 UTC
When searching for users via the client, the photo or photos property is always blank for returned users.

This may be by design, but I can't find examples or documentation on how to retrieve photo data when making requests.
(I can find examples for doing this with the current user, or a specific user, but not when searching/filtering).

This is an example of how I am making a request (as part of an ASP.NET core application):

```
    public async Task<IActionResult> OnGetUserSearch(string searchText)
    {
        var response = await graphServiceClient.Users
            .Request()
            .Filter($"(DisplayName eq '{searchText}' or startsWith(DisplayName, '{searchText}') or startsWith(GivenName, '{searchText}') or startsWith(Surname, '{searchText}')) and AccountEnabled eq true")
            .Select(x => new { x.DisplayName, x.GivenName, x.UserPrincipalName, x.Photos, x.Surname })
            .GetAsync();

        return Partial("_UserSearchResults", response.CurrentPage.OrderBy(u => u.DisplayName).ToList());
    }
```

Sometime later I am iterating over the response in my view. The photos property is always blank.

What else do I have to do to include it as part of the original request if that is even possible. If not, what is the work around?

Thanks for any help or advice.

**Comment by andrueastman** [comment] 2021-11-24 07:33
Hey @rmmcgr,

Thanks for raising this issue. I don't think the API supports using `Select` with the `Photo` property at the moment. You could always raise a feature request for the same at the link below.

https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform

To work around this, you could possibly take advantage of [json batching](https://docs.microsoft.com/en-us/graph/json-batching) to make a second request for photos for all the users returned in the search query. 
You can take a look at the example provided below,

```cs
// get the users matching the criteria
var users = await graphClient.Users
    .Request()
    .Filter($"(DisplayName eq '{searchText}' or startsWith(DisplayName, '{searchText}') or startsWith(GivenName, '{searchText}') or startsWith(Surname, '{searchText}')) and AccountEnabled eq true")
    .Select(x => new { x.DisplayName, x.GivenName, x.UserPrincipalName,  x.Surname , x.Photos , x.Photo})
    .Top(20) //limit to 20 since we can only do 20 batch messages at a go
    .GetAsync();

// create a request to fetch the users photos all at once.
var batchRequestContent = new BatchRequestContent();
foreach (var user in users)
{
    // use 'user.UserPrincipalName' as the key to use when extracting responses
    var batchRequestStep = new BatchRequestStep(user.UserPrincipalName,graphClient.Users[user.UserPrincipalName].Photo.Content.Request().GetHttpRequestMessage());
    batchRequestContent.AddBatchRequestStep(batchRequestStep);
}
// send the request
var batchResponse = await graphClient.Batch.Request().PostAsync(batchRequestContent);
// Read the response and match it with the user.
foreach (var user in users)
{
    // use 'user.UserPrincipalName' as the key to use when extracting responses
    var responseMessage = await batchResponse.GetResponseByIdAsync(user.UserPrincipalName);
    if (responseMessage.IsSuccessStatusCode)
    {
        var photoStream = responseMessage.Content.ReadAsStreamAsync(); //read the users photo
        // TODO place the photo where we need it.
    }
}
```

Closing this for now as the issue is mainly related to the API and not the client SDK.

**Closed by andrueastman** 2021-11-24 07:33 UTC
Labels: ToTriage

**Comment by rmmcgr** [comment] 2021-11-25 01:07
For reference, feature request submitted here:
https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/graph-api-support-for-photos-property-in-select/idi-p/3003886
