### ISSUE TITLE
https://graph.microsoft.com/v1.0/me/photo/$value gives 'ConsumerPhotoIsNotSupported' error code.

### ISSUE THREAD

**Issue by srnitk** [microsoftgraph/msgraph-sdk-dotnet#612] opened 2019-12-25 05:40 UTC
Calling Graph API to get user photo at the URL https://graph.microsoft.com/v1.0/me/photo/$value from the website https://developer.microsoft.com/en-us/graph/graph-explorer/preview gives following error:

{
    "error": {
        "code": "ConsumerPhotoIsNotSupported",
        "message": "The photo wasn't found.",
        "innerError": {
            "request-id": "987ea284-74f8-4078-8220-00d960ba3345",
            "date": "2019-12-25T05:35:02"
        }
    }
}

With response headers:
{
    "cache-control": "private",
    "client-request-id": "91fda261-c265-dacc-9f6d-e9d91f8b7b03",
    "content-length": "236",
    "content-type": "application/json",
    "request-id": "987ea284-74f8-4078-8220-00d960ba3345"
}

This used to work earlier, what am I missing to provide in the request? Or there is a bug in the syste? 
[AB#7264](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7264)

**Comment by peombwa** [comment] 2020-01-07 19:35
@srnitk from the [docs](https://docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0) getting a profile photo for a consumer account is not supported in v1.0 and only works in beta. This seems to be related to https://github.com/microsoftgraph/microsoft-graph-docs/issues/3990.

**Comment by andrueastman** [comment] 2021-05-19 14:48
Closing this for now as a duplicate of https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/568

**Closed by andrueastman** 2021-05-19 14:48 UTC
Labels: promote
