### ISSUE TITLE
IDriveItemInviteRequestBuilder - expirationDateTime wrong type

### ISSUE THREAD

**Issue by nvarelas777** [microsoftgraph/msgraph-sdk-dotnet#1055] opened 2021-06-18 23:36 UTC
### Expected behavior

Be able to add new permission for users to view item

### Actual behavior

Receiving null exception

https://docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&tabs=http

expirationDateTime is of type DateTimeOffset in the docs.

Here it is in the interface
IDriveItemInviteRequestBuilder Invite(IEnumerable<DriveRecipient> recipients, bool? requireSignIn = null, IEnumerable<string> roles = null, bool? sendInvitation = null, string message = null, string expirationDateTime = null, string password = null);

CreateLink also uses expirationDateTime in the same class 
IDriveItemCreateLinkRequestBuilder CreateLink(string type, string scope = null, DateTimeOffset? expirationDateTime = null, string password = null, string message = null);

### Steps to reproduce the behavior

var list = new List<DriveRecipient>(){new DriveRecipient{Email = "ryan@contoso.com"}}
var document = await graphClient.Sites[{siteId}]
.Drive
.Items[{itemId}]
.Invite(list, true, new List<string>(){"read"}, true, "i'm broken", "2018-07-15T14:00:00Z")
.Request()
.PostAsync();

 
[AB#9969](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9969)

**Comment by andrueastman** [comment] 2021-07-05 08:11
Thanks for raising this issue @nvarelas777.

This looks to be a duplicate of #1027. 

Closing this for now so that the issue may be followed up there.

**Closed by andrueastman** 2021-07-05 08:11 UTC
