### ISSUE TITLE
OneDrive File Upload (any size / any location: personal and shared folders)

### ISSUE THREAD

**Issue by horacioj** [microsoftgraph/msgraph-sdk-dotnet#61] opened 2016-11-03 13:43 UTC
Follow up (here, as requested) for the [stackoverflow question about OneDrive Large File Upload (> 4MB in size)](http://stackoverflow.com/questions/39988568/microsoft-graph-net-sdk-onedrive-large-file-upload-4mb-in-size) about this issue.

I tested the code in the [/MIchaelMainer/working branch](https://github.com/microsoftgraph/msgraph-sdk-dotnet/tree/MIchaelMainer/working), and it worked fine. 
I was able to upload a 1.5GB file. Great!

Now, the problem is, I couldn't find any way to [upload files to a shared folder](https://stackoverflow.com/questions/40369180/microsoft-graph-uploading-files-to-shared-library-instead-of-users-library). 

I couldn't find any suitable method in the [API documentation](https://graph.microsoft.io/en-us/docs/api-reference/v1.0/api/item_uploadcontent).  Neither PUT nor using  an Upload Session. So, I don't think this is a limitation of the SDK, but in the API itself.

I find this very weird. I'm able to do anything (create/rename/delete folders, list, delete/rename/download files...) with items in shared folders except uploading files? 
This invalidates everything I was doing :( 

Can someone at MS point me to the right direction, or at least be so kind to at least confirm this is really missing from the API? Nobody said anything in [stackoverflow](https://stackoverflow.com/questions/40369180/microsoft-graph-uploading-files-to-shared-library-instead-of-users-library).

Thanks

**Comment by horacioj** [comment] 2016-11-04 23:45
>I tested the code in the /MIchaelMainer/working branch, and it worked fine.

Actually, it does work for work accounts, but it fails ("Authentication failed") for personal accounts. The documentation doesn't says anything about this being a work accounts feature only. Perhaps it is? Or is the a bug? If it is a bug, I don't see where this could be, because the single difference is the account type.

**Comment by ificator** [comment] 2016-11-07 23:07
I'm not all that familiar with the referenced code, but I believe the issue is that Graph authentication is being provided on a request that isn't actually going to a Graph endpoint. It turns out that while OneDrive for Business handles this, OneDrive for Consumers does not. Realistically the consumer endpoint should also accept the request since the URL itself possesses the required authentication, however the solution to quickest resolution will be to make sure the PUT requests for fragments **DO NOT** include an `Authorization` header.

**Comment by horacioj** [comment] 2016-11-07 23:21
Thanks for your comment. I'll see if I can do anything regarding the chunked upload to a personal accounts (try (I'm not sure how) to avoid sending the the authorization header for fragments) .


I'm still clueless about the other issue I've mentioned in the first post. Do you know how can I upload to a shared folder (e.g. the default "https://mycompany.sharepoint.com/Shared%20Documents" folder? I don't see any suitable option in the [Microsoft Graph API Documentation](https://graph.microsoft.io/en-us/docs/overview/overview). 

Many thanks.

**Comment by ificator** [comment] 2016-11-07 23:23
Do you happen to have a list of the scopes that are present in the access token being used for the request to create the upload session?

**Comment by horacioj** [comment] 2016-11-07 23:43
>a list of the scopes 

Yes: 

    openid profile offline_access User.Read Files.ReadWrite Files.ReadWrite.All

I don't think that's the problem, though. The problem is I don't see any option (in the API) to POST or create an Upload Session for a SharePoint folder. 

For instance, the [simple upload](https://graph.microsoft.io/en-us/docs/api-reference/v1.0/api/item_uploadcontent)  (using PUT) show these options:

    PUT /me/drive/items/{parent-id}:/{filename}:/content
    PUT /me/drive/root:/{parent-path}/{filename}:/content
    PUT /me/drive/items/{parent-id}/children/{filename}/content
    PUT /groups/<id>/drive/items/<parent-id>/children/<filename>/content

All refers to "me" (user's drive), except the last one which I think is for something else.
To list items I can: 

    GET /me/drive/root/children  => lists your personal drive. 
    GET /drive/root/children  => lists the content of your organization's drive/SharePoint site.
    GET /drives/{drive-id}/items/{item-id}/children  => lists the content of the specified drive id

I've got invalidRequest ("A valid path must be provided.") for any PUT I've tried, looking for a way to upload to the organization's drive/SharePoint site.

**Comment by ificator** [comment] 2016-11-08 00:03
Thanks - I wanted to confirm you had `Files.ReadWrite.All` so we're good on that front!

Provided you know the drive and item ids to the shared folder you should be able to make `POST` call to something like the following to create the session:

```
POST /v1.0/drives/{drive-id}/items/{item-id}:/newfile.txt:/createUploadSession
Authorization: bearer <token>
Content-Type: application/json
```

And body:

```
{
}
```

You can have similar URLs for doing a direct `PUT` - but be ware of the size limits for files uploaded via that approach:

```
PUT /v1.0/drives/{drive-id}/items/{item-id}:/newfile.txt:/content
```

or

```
PUT /v1.0/drives/{drive-id}/items/{item-id}/children/newfile.txt/content
```

**Comment by horacioj** [comment] 2016-11-08 00:29
Are you sure this should work?

    POST /v1.0/drives/{drive-id}/items/{item-id}:/newfile.txt:/createUploadSession

For example, in the Graph Explorer, the response for this:

    POST /v1.0/drives/THEDRIVEID/items/THEFOLDERID:/newfile.txt:/createUploadSession

was:

    Status Code: 400
    
    {
        "error": {
            "code": "invalidRequest",
            "message": "A valid path must be provided.",
            "innerError": {
                "request-id": "0aeefb1a-5cce-42a9-99fa-2274dbec6d66",
                "date": "2016-11-08T00:27:23"
            }
        }
    }

I know the IDs are OK, because this works fine:

    GET https://graph.microsoft.com/v1.0/drives/THEDRIVEID/items/THEFOLDERID/children

**Comment by ificator** [comment] 2016-11-08 22:43
It should - it looks like there's an issue that's causing it to fail currently. I'm following up to resolve that.

**Comment by horacioj** [comment] 2016-11-14 15:23
Hi,
Do you have any update on this?
Thanks

**Comment by ificator** [comment] 2016-11-14 16:25
It looks as though the developer assigned to the issue was on vacation last week, so hopefully we'll see some traction this week.

**Comment by JogyBlack** [comment] 2016-12-18 13:08
Hi,

We have similar problem - the chunked upload won't work, returning Unauthorized error code.

I implemented workaround - in the AuthenticationHelper class placed a flag 
```
    public static bool TurnOffAuth { get; set; }

    public static GraphServiceClient GetAuthenticatedClient()
    {
      if (graphClient == null)
      {
        // Create Microsoft Graph client.
        try
        {
          graphClient = new GraphServiceClient(
              "https://graph.microsoft.com/v1.0",
              new DelegateAuthenticationProvider(
                  async (requestMessage) =>
                  {
                    if (!TurnOffAuth)
                    {
                      var token = await GetTokenForUserAsync();
                      requestMessage.Headers.Authorization = new AuthenticationHeaderValue("bearer", token);
                    }
                  }));
          return graphClient;
        }
        catch (Exception ex)
        {
          Debug.WriteLine("Could not create a graph client: " + ex.Message);
        }
      }
      return graphClient;
    }
```

and then set this flag when uploading the chunks.
This workaround works with the released NuGet package.

**Comment by cbales** [comment] 2016-12-19 23:51
Thanks for the comment. We will be integrating a solution into the library soon.

**Closed** 2017-02-27 17:41 UTC

**Comment by pratik-c** [comment] 2018-01-17 11:54
I'm getting  response 404 status code "File name not provided in url"... can someone please help,
my request looks like

POST /v1.0/drives/{drive-id}/items/{item-id}/createUploadSession
Authorization: bearer <token>
Content-Type: application/json

without any body

**Comment by Brian-Paquette** [comment] 2018-04-13 18:38
Hey i noticed you guys seem to know what's going on. Could anyone please tell help me with uploading a new file to onedrive? I have managed to update an existing file, but creating a new one is giving me trouble. Here is the line i used to update an existing onedrive file. await client.Me.Drive.Items["55BBAC51A4E4017D!104"].Content.Request().PutAsync<DriveItem>(stream);

Here is my stack post with full code: https://stackoverflow.com/questions/49822779/upload-new-file-to-onedrive-using-microsoft-graph-c-sharp-asp-net

**Comment by MIchaelMainer** [comment] 2018-04-16 20:02
@Brian-Paquette Please post *How do I...* questions to StackOverflow with the [microsoft-graph] tag. I've asked a clarifying on the SO post in case your are still working on this issue.
