### ISSUE TITLE
Error uploading user profile picture

### ISSUE THREAD

**Issue by danpardo** [microsoftgraph/msgraph-sdk-dotnet#234] opened 2018-01-25 23:47 UTC
Please provide the following (and please check them off the list with [x]) before submitting this issue:
- [x] Expected behavior. Please provide **links to the specific [Microsoft Graph documentation](https://developer.microsoft.com/en-us/graph/docs/concepts/overview)** you used to determine the expected behavior. 
- [x] Actual behavior. Provide error codes, stack information, and a [Fiddler](http://www.telerik.com/fiddler) capture of the request and response (please remove personally identifiable information before posting).
- [x] Steps to reproduce the behavior. Include your code, IDE versions, client library versions, and any other information that might be helpful to understand your scenario.

### Expected behavior
Calling graphServiceClient.Users[userGuid].Photo.Content.Request().PutAsync(stream) should upload the stream image for the user specified.

### Actual behavior
It just throws an error, Request is invalid no further information.

### Steps to reproduce the behavior
User is of userType Guest in our Azure AD. When trying to upload a profile picture for a Member it doesn't throw an error but it doesn't upload the picture either. All other calls are working fine, picture uploaded using the Azure AD portal also works.

**Comment by MIchaelMainer** [comment] 2018-01-26 00:13
Please provide the Fiddler capture and a link to the documented expected behavior.

What is a Guest userType? Provide link to the documentation.
What do you mean by a 'Member'? Member of what?

**Comment by MIchaelMainer** [comment] 2018-01-30 23:38
Closing this since the requested follow up information hasn't been provided. Please reopen when you can provide more information about this issue.

**Closed by MIchaelMainer** 2018-01-30 23:38 UTC
