### ISSUE TITLE
Unable to use Patch to update a SingleValueExtendedProperty on an Event.

### ISSUE THREAD

**Issue by georgenell** [microsoftgraph/msgraph-sdk-dotnet#1807] opened 2023-04-05 04:46 UTC
Updating the value of an existing SingleValueExtendedProperty on an Event does not work as the resulting message excludes the ID which is required for the change.

**To replicate**
```csharp
// Read an existing Event, with an Expand filter requesting
// my two Extended Properties in the expansion filter
Event currentEvent = await _msGraph.Users[graphUserId].Events[eventId].GetAsync((requestConfiguration) =>
{
	requestConfiguration.QueryParameters.Expand = new string[] { "singleValueExtendedProperties($filter=(" +
		"id eq 'Integer {00020329-0000-0000-c000-000000000046} Name CustomId' or " +
		"id eq 'String {00020329-0000-0000-c000-000000000046} Name CustomValue'" +
		"))" };
});

// Update one of the values
currentEvent.SingleValueExtendedProperties[1].Value = "Test String";

// Attempt to save the changes
Event updatedEvent = await _msGraph.Users[graphUserId].Events[eventId].PatchAsync(currentEvent);
// ^ This throws an exception
```

The exception thrown contains the following ODataError detailing the issue:
```
Code: ErrorInvalidProperty
Message: PropertyId values may only be in one of the following formats: 'MapiPropertyType namespaceGuid Name propertyName', 'MapiPropertyType namespaceGuid Id propertyId' or 'MapiPropertyType propertyTag'.
```
**Explanation**
The reason why it fails can be found by writing an extension to extract the HttpRequestMessage and looking at the JSON.
The value we're trying to send to the server is:
```json
{"singleValueExtendedProperties":[{},{"value":"Test String"}]}
```

Trying that in the Graph Explorer also fails, and we can see why:
1. The the ID is required to update the ExtendedProperty.
2. The empty node from the unchanged property needs to be removed.

If I manually fix the JSON and submit it like this, the update succeeds:
```json
{"singleValueExtendedProperties":[{"id":"String {00020329-0000-0000-c000-000000000046} Name CustomValue","value":"Test String"}]}
```

With that knowledge I have written an extension method that I can use to make these updates successfully, so this issue is non-blocking.

My testing is in C# under .NET Framework 4.7.2 on Windows with NuGet packages
- Microsoft.Graph - 5.4.0
- Microsoft.Graph.Core - 3.0.5

My requirement is only for single value properties on Events, so I have not tested MultiValueExtendedProperties or extended properties on any other object type, others may also suffer from this issue.

**Comment by MartinM85** [comment] 2023-04-05 06:31
Could you confirm that `id` of `singleValueExtendedProperties` returned by the call contains the value or is it empty?

```
Event currentEvent = await _msGraph.Users[graphUserId].Events[eventId].GetAsync((requestConfiguration) =>
{
	requestConfiguration.QueryParameters.Expand = new string[] { "singleValueExtendedProperties($filter=(" +
		"id eq 'Integer {00020329-0000-0000-c000-000000000046} Name CustomId' or " +
		"id eq 'String {00020329-0000-0000-c000-000000000046} Name CustomValue'" +
		"))" };
});
```
It looks like that it can be the root cause

```
currentEvent.SingleValueExtendedProperties[0].Id
currentEvent.SingleValueExtendedProperties[1].Id
```

I'm using similar code to update `SingleValueExtendedProperties` on `Event`  and it works fine

    var body = new Event
    {
        SingleValueExtendedProperties = new List<SingleValueLegacyExtendedProperty>
        {
            new SingleValueLegacyExtendedProperty
            {
                Id = propertyId,
                Value = propertyValue
            }
        }
    };
    await _client.Me.Events[eventId].PatchAsync(body);

**Comment by georgenell** [comment] 2023-04-05 08:41
Sorry I should have made that clear - yes the `Id` values are populated correctly in the object obtained by the Get request.

Your example is a little different I think, as you're creating a new model rather than updating an existing one. The way the client uses the backing store to create a minimal message with just the dirty changes is the cause of my issue. As only the ExtendedProperty's Value was changed, that is the only element that it sends back to the server, which isn't enough for it to succeed.

As explained in the [v5 upgrade guide here](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/5.0/docs/upgrade-to-v5.md#backing-store).

**Comment by andrueastman** [comment] 2023-04-06 08:28
Thanks for following up @georgenell.

Just to confirm, as you have identified the issue, is the ask here to have the backingStore emit the id property as well? Or can we close this one?

**Comment by georgenell** [comment] 2023-04-06 09:24
From an end-user developer experience perspective, I think the ideal solution is to have the backing store emit valid json that will succeed to update the event. While workarounds do exist, all the other fields (that I've tried) update correctly.

It could be documented that a developer needs to touch the `Id` property as well to ensure both Id and Value are emitted in the json, but that doesn't solve the issue of the empty `{},` nodes for any untouched ExtendedProperty. Having to manually touch each of those too, even if no changes are required, complicates the update code much more.

The alternative to a fix is to document that those extended properties cannot be changed when using the backing store, they can only be set from a new object, as @MartinM85 shows above.

**Comment by andrueastman** [comment] 2023-08-17 08:35
This should be resolved in the latest versions of the SDK after the updates made via https://github.com/microsoft/kiota-abstractions-dotnet/pull/84

**Closed by andrueastman** 2023-08-17 08:35 UTC
Labels: Bug: documentation, Status: Needs investigation
