### ISSUE TITLE
CallRecord response from Graph dotnet doesn't match Graph API response when participant is a phone number

### ISSUE THREAD

**Issue by przeciag** [microsoftgraph/msgraph-sdk-dotnet#1214] opened 2022-01-05 10:52 UTC
**Describe the bug**
When calling `/communications/callRecords` Graph API via dotnet sdk response isn't in line with response I'm receiving via regular Graph API call out, as phone number is neither included as participant nor organizer (if should be). Same happens with `sessions` when I'm querying for those as well, there is no identity of `phone` involved in a call

**To Reproduce**
1. Have a subscription to `/communications/callRecords` 
2. When Id is received make a callout via sdk 
3. Make same request via API and compare response

**Expected behavior**
API returns `phone` object with phone number included as an id
` "phone": {
      "id": "+00123456789",
      "displayName": null,
      "tenantId": null
    }`

SDK doesn't return `phone` object

**Comment by andrueastman** [comment] 2022-01-05 12:47
Hey @przeciag,

Thanks for raising this issue. 

Are you able to share a sample payload of the object returned when you make the call and the version of the SDK you are using to help us understand the issue better?

**Comment by przeciag** [comment] 2022-01-05 13:06
Hi @andrueastman ,
This is sample payload from SDK, where `Organizer` was phone number (External)
`  "Organizer": {
    "Application": null,
    "Device": null,
    "User": null,
    "AdditionalData": {},
    "ODataType": null
  }`

For comparison, same `Organizer` from Graph API:
` 
"organizer": {
    "user": null,
    "phone": {
      "id": "+44123456789",
      "displayName": null,
      "tenantId": null
    },
    "application": null,
    "device": null
  }
`
Behaviour would be the same  if `phone` would be a `Participant` in a call
I'm using SDK ver 4.13.0

**Comment by andrueastman** [comment] 2022-01-05 13:16
Thanks for this. 

According to the metadata, the organizer property is defined with the [IdentitySet](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/src/Microsoft.Graph/Generated/model/IdentitySet.cs) type. This type doesn't have the member with the property name "Phone". 

This means if the response has an extra property, it would be placed inside the AdditionalData bag. Any chance you can check if there is an object in the AdditionalData bag that has the key "phone"?

**Comment by przeciag** [comment] 2022-01-05 15:06
I've tried this, and it does exists, but it's only represented as `{"ValueKind":1}` when given object is a phone, and `{"ValueKind":7}` when it's MS Teams user.

**Comment by andrueastman** [comment] 2022-01-06 05:56
That could possibly be explained by the fact that the object is of the type `JsonElement` which is the type the serializer uses for "unknown" properties.

Any chance you now see something the contents if you do something like this?

```cs
var phoneJsonObject = organizer.AdditionalData["phone"] as JsonElement;
var jsonString = phoneJsonObject.GetRawText();
Console.WriteLine(jsonString);
```

**Comment by przeciag** [comment] 2022-01-06 10:02
I did try that, and it indeed works, also I've tried using standard .NET JsonSerializer library instead of Newtonsoft.Json, and it did serialize it same response as Graph API response 

`var phoneJsonObject = (System.Text.Json.JsonElement)callRecord.Organizer.AdditionalData["phone"];`

returned:
`{"id":"+441234567890","displayName":null,"tenantId":null}`

**Comment by andrueastman** [comment] 2022-01-06 11:35
Glad to hear it worked out @przeciag. 

Version 4 of the SDK dropped support for NetwonSoft to use System.Text.Json and will have incompatibilities if you try to use NewtonSoft on our models.

I believe the issue is now resolved and will be closing this for now. Feel free to reopen if there's anything else.

**Closed by andrueastman** 2022-01-06 11:35 UTC
Labels: Needs: Attention :wave:
