### ISSUE TITLE
Unable to upload file which contains "#" in the file name

### ISSUE THREAD

**Issue by andrew-vdb** [microsoftgraph/msgraph-sdk-dotnet#487] opened 2019-06-03 14:25 UTC
We tested with '@', '%', '&', file was uploaded successfully.

### Expected behavior
File uploaded.

### Actual behavior
Microsoft.Graph.ServiceException, Microsoft.Graph.Core
"generalException"
Unexpected exception returned from the service.
ResponseCode 400

```
at Microsoft.Graph.HttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.BaseRequest.SendAsync[T](Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
```

### Steps to reproduce the behavior
Upload file which contains '#' in the file name

**Comment by MIchaelMainer** [comment] 2019-06-03 14:51
This is a duplicate of #147. Need to URL encode the filename.

**Comment by andrew-vdb** [comment] 2019-06-04 06:51
The problem is I don't need to encode '@', '%', '&', why I need to encode '#' only?

**Closed** 2019-06-05 07:00 UTC
Labels: ToTriage, duplicate
