### ISSUE TITLE
v5 missing support for Sites.GetByPath

### ISSUE THREAD

**Issue by JohanKroese** [microsoftgraph/msgraph-sdk-dotnet#1698] opened 2023-03-09 10:15 UTC
**Describe the bug**
The new SDK no longer contains a way to retrieve SharePoint sites based on the path of the site. 

**To Reproduce**
My Graph SDK v4 code was:
`var site = await graphClient
				.Sites
				.GetByPath(siteUrl, host)
				.Request()
				.GetAsync();`

The .GetByPath method disappeared in V5. Using the requestConfiguration we can add queryparameters and filters but I don't see a way to add the path. The SDK no longer seems to support [https://learn.microsoft.com/en-us/graph/api/site-getbypath?view=graph-rest-1.0](url) or I cannot find it.

**Expected behavior**
Support for the GetByPath Graph API call.

**Comment by andrueastman** [comment] 2023-03-10 10:23
Closing as duplicate of https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1693

**Closed by andrueastman** 2023-03-10 10:23 UTC
