### ISSUE TITLE
AccessPackageFilterByCurrentUserOptions.AllowedRequestor enum is not added properly to url as a string

### ISSUE THREAD

**Issue by mbukovich** [microsoftgraph/msgraph-sdk-dotnet#1279] opened 2022-03-15 22:28 UTC
**Describe the bug**
When this function is used: AccessPackages.FilterByCurrentUser(AccessPackageFilterByCurrentUserOptions.AllowedRequestor)
The SDK generates this URL:
https://graph.microsoft.com/v1.0/identityGovernance/entitlementManagement/accessPackages/microsoft.graph.filterByCurrentUser(on=AllowedRequestor) 
Whereas, the URL should be:
https://graph.microsoft.com/v1.0/identityGovernance/entitlementManagement/accessPackages/filterByCurrentUser(on='allowedRequestor')

Basically, 'allowedRequestor' needs to be added to the URL with single quotes, but is added without quotes

Error:
System.AggregateException: 'One or more errors occurred. (Code: BadRequest
Message: The parameter 'on=AllowedRequestor' is not in scope.
Inner error:
	AdditionalData:
	date: 2022-03-12T00:41:08
	request-id: 4cc415e6-5f2a-4234-972f-6035c77b7bfc
	client-request-id: 4cc415e6-5f2a-4234-972f-6035c77b7bfc
ClientRequestId: 4cc415e6-5f2a-4234-972f-6035c77b7bfc
)'

**To Reproduce**
1. In an application with the MSGraph SDK setup and working, add the following code (making any adjustments necessary to work with existing code):
```
var filterByCurrentUser = await graphClient.IdentityGovernance.EntitlementManagement.AccessPackages
     .FilterByCurrentUser(AccessPackageFilterByCurrentUserOptions.AllowedRequestor)
     .Request()
     .GetAsync();
```
2. Run the code and review the error generated. For example, I received this error:
System.AggregateException: 'One or more errors occurred. (Code: BadRequest
Message: The parameter 'on=AllowedRequestor' is not in scope.
Inner error:
	AdditionalData:
	date: 2022-03-12T00:41:08
	request-id: 4cc415e6-5f2a-4234-972f-6035c77b7bfc
	client-request-id: 4cc415e6-5f2a-4234-972f-6035c77b7bfc
ClientRequestId: 4cc415e6-5f2a-4234-972f-6035c77b7bfc
)'

**Expected behavior**
Expect for this query to be issued:
https://graph.microsoft.com/v1.0/identityGovernance/entitlementManagement/accessPackages/filterByCurrentUser(on='allowedRequestor')

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: NA
 - Version: NA

**Smartphone (please complete the following information):**
 - Device: NA
 - OS: NA
 - Browser: NA
 - Version: NA

**Additional context**

**Comment by zengin** [comment] 2022-03-18 18:10
Hi @mbukovich, this is a known issue from the code generator side. Closing this issue as duplicate of https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1156

**Closed by zengin** 2022-03-18 18:10 UTC
Labels: Needs: Triage
