### ISSUE TITLE
Setting Icon on an Application Fails with invalid Content-Type

### ISSUE THREAD

**Issue by eamreyes** [microsoftgraph/msgraph-sdk-dotnet#1863] opened 2023-04-28 02:25 UTC
# Bug
The request to update an application's icon fails with an invalid Content-Type error.

## Reproduction Steps
1. Add Graph SDK 5.7.0 to project
2. Create a memory stream of an icon. `var stream = new MemoryStream(logoBytes);`
3. Invoke the API `var logoTask = _graph.Applications[applicationId].Logo.PutAsync(stream)`

**Expected Behavior**
Expected to upload icon to target application

**Actual Behavior**
Runtime exception

`Content-Type was application/octet-stream. Image Content-Type header should be one of the following: [image/bmp, image/emf, image/wmf, image/jpg, image/jpeg, image/gif, image/ico, image/png, image/exif, image/tif, image/tiff, image/*, images/*]`

### Attempt 1 At workaround
Tried to set the Content-Type via configuration but the octect-stream is still added to the Content-Type and leads to a runtime exception.
```csharp
var logoRequestInfo = _graph.Applications[applicationId].Logo.PutAsync(stream, config => {
config.Headers.Headers.Remove("Content-Type");
config.Headers.Add("Content-Type", "image/png");
});

```
`Content-Type was application/octet-stream, image/png. Image Content-Type header should be one of the following: [image/bmp, image/emf, image/wmf, image/jpg, image/jpeg, image/gif, image/ico, image/png, image/exif, image/tif, image/tiff, image/*, images/*]`

### Workaround

Building the PutRequestInformation, then modifying the Content-Type, results in a successful request.

```csharp
var logoRequestInfo = _graph.Applications[applicationId].Logo.ToPutRequestInformation(stream);
logoRequestInfo.Headers.Remove("Content-Type");
logoRequestInfo.Headers.Add("Content-Type", "image/*");
var logoTask = _graph.RequestAdapter.SendPrimitiveAsync<Stream?>(logoRequestInfo);
```

**Comment by andrueastman** [comment] 2023-06-15 10:00
Closing as duplicate of https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1951

**Closed by andrueastman** 2023-06-15 10:00 UTC
Labels: Bug, P2
