### ISSUE TITLE
.Net 8 upgrade 

### ISSUE THREAD

**Issue by salladorets** [microsoftgraph/msgraph-sdk-dotnet#2222] opened 2023-11-16 13:59 UTC
The following warning appeared after update to .Net 8. (SDK version 5.34.0).  
Looks like application works fine, only the warnings appeared. 
`
Detected package version outside of dependency constraint: Microsoft.Kiota.Http.HttpClientLibrary 1.3.0 requires System.Text.Json (>= 6.0.0 && < 8.0.0) but version System.Text.Json 8.0.0 was resolved.`
 
`Detected package version outside of dependency constraint: Microsoft.Kiota.Serialization.Json 1.1.1 requires System.Text.Json (>= 6.0.0 && < 8.0.0) but version System.Text.Json 8.0.0 was resolved.`

**Comment by andrueastman** [comment] 2023-11-16 14:10
Thanks for raising this @salladorets 

This should be resolved with latest update available at https://www.nuget.org/packages/Microsoft.Graph/5.35.0

Closing this as a duplicate of https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2214

**Closed by andrueastman** 2023-11-16 14:10 UTC
