### ISSUE TITLE
Unable to convert an OpenXml document to PDF

### ISSUE THREAD

**Issue by Arash-Sabet** [microsoftgraph/msgraph-sdk-dotnet#1710] opened 2023-03-10 19:17 UTC
**Describe the bug**
We used to be able to have an OpenXML file converted to PDF using the code snippet below:

```csharp
var queryOptions = new List<QueryOption>()
{
	new QueryOption("format", "pdf")
};
var pdf = await graphClient
	.Users["someUserId"]
	.Drive
	.Items["fileId"]
	.Content
	.Request(queryOptions)
	.GetAsync(cancellationToken);
````
This goal cannot be achieved by the new API. Please see the following section.
**To Reproduce**
Use the following code snippet to save `pdfStream` to a file with PDF extension on your disk. Acrobat reader or any other tools fail to open the file. Rename the PDF file's extension to 'docx' and you will be able to see the saved document's contents by MS Word!

```cs
var requestBuilder = graphClient
   .DirectoryObjects
   .ToGetRequestInformation(config => config.QueryParameters.Filter = "format=pdf");
var pdfStream = await graphClient.Drives[drive.Id].Items[item.Id].Content.GetAsync(c => c.Options = requestBuilder.RequestOptions.ToList(), cancellationToken);
```
Even trying other possible variants e.g. `config.QueryParameters.Filter ="format eq 'pdf'"` or `config.QueryParameters.Filter ="format eq pdf"` is not conclusive.

**Expected behavior**
A valid PDF file should be generated.

**Screenshots**

**Client version**
Version 5.0

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: n/a
 - Version: n/a

**Additional context**
n/a

**Comment by andrueastman** [comment] 2023-03-14 08:33
Thanks for raising this @Arash-Sabet 

We'll close this as a duplicate of https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1621 where a workaround exists as we fix the metadata.

**Closed by andrueastman** 2023-03-14 08:33 UTC
Labels: Bug: metadata, OpenApi
