### ISSUE TITLE
Create Website Tab on channel on MSTeams - InternalServerError - Error while processing response

### ISSUE THREAD

**Issue by kudecha** [microsoftgraph/msgraph-sdk-dotnet#594] opened 2019-11-24 22:37 UTC
Hi,

I am using API v1.20.0 in my web Application to communicate with O365 data.
I am facing an issue while creating a new Website Tab on General Channel for a team on Microsoft Teams.
I am using Microsoft.Graph API application credentials to achieve above task. However, unable to successfully complete the create website tab task.

Here is my code.
`TeamsTab objTeamsTab = new TeamsTab();
objTeamsTab.ODataBind = "https://graph.microsoft.com/v1.0/appCatalogs/teamsApps/com.microsoft.teamspace.tab.web";
            //objTeamsTab.AdditionalData = new Dictionary<string, object>();
            //objTeamsTab.AdditionalData.Add("teamsApp@odata.bind", "https://graph.microsoft.com/v1.0/appCatalogs/teamsApps/com.microsoft.teamspace.tab.web");
objTeamsTab.DisplayName = "Test1";
objTeamsTab.Configuration = new TeamsTabConfiguration();
objTeamsTab.Configuration.ContentUrl = "https://www.microsoft.com";
objTeamsTab.Configuration.WebsiteUrl = "https://www.microsoft.com";
var result = await mainGraphClient.Teams[{GroupId}].Channels[{ChannelId}].Tabs.Request().AddAsync(objTeamsTab);`

FYI, {GroupId} & {ChannelId} are replaced with correct ids.
I have also tried to set teamsApp field using AdditionalData as well, which does not help either.

This code throws exception as below:
{
    "error": {
        "code": "InternalServerError",
        "message": "Error while processing response.",
        "innerError": {
            "request-id": "01375ab1-4e0c-45b1-aa2f-5bd1c9a3264f",
            "date": "2019-11-24T22:10:57"
        }
    }
}

Now, It starts throwing the same error even when trying to retrieve all tabs on this group/channel using App as well as Graph-Explorer until the recently created tab is removed from MSTeams.

Out of curiosity, I tried Graph-Explorer to create the tab, which successfully created tab and retrieval of all tabs still works. Here is the body:
{
  "displayName": "Test1",
  "teamsApp@odata.bind": "https://graph.microsoft.com/v1.0/appCatalogs/teamsApps/com.microsoft.teamspace.tab.web",
  "configuration": {
    "contentUrl": "https://www.microsoft.com",
    "websiteUrl": "https://www.microsoft.com",
  }
}

I checked the request using fiddler when it is sent from my application, and the only difference i could see when compared to above is @odata.type tags.
Fiddler shows following json when request is sent from app, which creates tab but fails on providing response, and all requests after that to retrieve all tabs. Here is the body captured from fiddler:
{
"teamsApp@odata.bind":"https://graph.microsoft.com/v1.0/appCatalogs/teamsApps/com.microsoft.teamspace.tab.web",
"displayName":"Test1",
"configuration":{
    "contentUrl":"https://www.microsoft.com",
    "websiteUrl":"https://www,microsoft.com",
    "@odata.type":"microsoft.graph.teamsTabConfiguration"},
    "@odata.type":"microsoft.graph.teamsTab"
}

Would you please check this out and provide me with the best way to handle this?

Thanks,
Jay

**Comment by MIchaelMainer** [comment] 2019-11-25 17:51
This is a duplicate of https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/566. 

We started generating the client library with the odata.type set on all objects. The Team service doesn't ignore the odata.type property as is expected. 

The mitigation will be for you to set the `ODataType = null`. I'm sorry for this inconvenience.

**Closed** 2019-12-02 19:00 UTC
Labels: Needs: Author Feedback, no-recent-activity
