### ISSUE TITLE
Creation of Channel via Graph API failes for certain Teams.

### ISSUE THREAD

**Issue by adrichema** [microsoftgraph/msgraph-sdk-dotnet#503] opened 2019-07-01 07:09 UTC
Since last Friday the 28th of June. For some teams I receive the following error when creating a Channel for a Team via de Graph API. Please note that the Teams are all created via Graph API as well.

Code: AccessDeniedMessage: Unable to fetch team thread: Failed to execute Skype backend request GetThreadS2SRequest.Inner error

Method: POST
BODY 
{
  "displayName": "TEST CHANNEL",
  "description": "PLEASE DO REMOVE THIS CHANNEL"
}

On these 3 Teams it fails:
https://graph.microsoft.com/v1.0/teams/06ce7c9d-92c7-407c-bf58-a840435f2927/channels
https://graph.microsoft.com/v1.0/teams/666c3cfa-ff2f-41f4-a4c0-0bcec7a92cee/channels
https://graph.microsoft.com/v1.0/teams/b860e15c-150b-48e0-8b57-f9374f0064a0/channels

On this Team it is working fine:
https://graph.microsoft.com/v1.0/teams/6c399095-04a4-4eee-bdca-b85121f5ff94/channels

Powershell is also failing, with bot app and user credentials. Creating a channel via the Teams client is working fine for both Teams.  
[AB#7294](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7294)

**Comment by MIchaelMainer** [comment] 2019-07-09 21:39
Thank you for reporting this issue. This appears to be an issue with the service API. This repository is specific to the .Net client library. 

Are you still experiencing this issue?

**Comment by adrichema** [comment] 2019-07-10 19:14
Thanks for replying. I am still experiencing the issue with some teams. Other teams are working just fine. All teams are created using the Graph API in exactly the same way.

**Comment by RamjotSingh** [comment] 2019-07-11 01:09
@adrichema Can you share a few requestIds for the issue?

**Comment by adrichema** [comment] 2019-07-11 09:37
@RamjotSingh, here are some requestIds of failed requests...

{
    "error": {
        "code": "AccessDenied",
        "message": "Unable to fetch team thread: Failed to execute Skype backend request GetThreadS2SRequest.",
        "innerError": {
            "request-id": "4b86a7a2-a5ab-4e13-957d-b2009b39d560",
            "date": "2019-07-11T09:36:40"
        }
    }
}

{
    "error": {
        "code": "AccessDenied",
        "message": "Unable to fetch team thread: Failed to execute Skype backend request GetThreadS2SRequest.",
        "innerError": {
            "request-id": "6f4163d9-d2e7-4d7f-8e29-9be87c541598",
            "date": "2019-07-11T09:37:24"
        }
    }
}

**Comment by RamjotSingh** [comment] 2019-07-11 17:50
@adrichema Are you trying to access the channel\team in application context or in delegated mode?

**Comment by adrichema** [comment] 2019-07-12 09:07
@RamjotSingh, I tried both, the failed request-id's are from the Graph Explorer which is in delegated mode (I assume).

**Comment by RamjotSingh** [comment] 2019-07-13 03:24
@adrichema Can you try again? We made a few fixes, want to see if this is still happening. If you face the error. Please share the new requestIds.

**Comment by adrichema** [comment] 2019-07-15 06:48
@RamjotSingh, thanks for your update.

I tried to create channels for the 3 teams mentioned in the opening post.

**On this team it works now:**
https://graph.microsoft.com/v1.0/teams/06ce7c9d-92c7-407c-bf58-a840435f2927/channels

**On these teams it does not work:**
https://graph.microsoft.com/v1.0/teams/666c3cfa-ff2f-41f4-a4c0-0bcec7a92cee/channels
{
    "error": {
        "code": "AccessDenied",
        "message": "Unable to fetch team thread: Failed to execute Skype backend request GetThreadS2SRequest.",
        "innerError": {
            "request-id": "5d4c7e6f-f339-4476-86bd-014149612599",
            "date": "2019-07-15T06:44:46"
        }
    }
}

https://graph.microsoft.com/v1.0/teams/b860e15c-150b-48e0-8b57-f9374f0064a0/channels
{
    "error": {
        "code": "AccessDenied",
        "message": "Unable to fetch team thread: Failed to execute Skype backend request GetThreadS2SRequest.",
        "innerError": {
            "request-id": "b0b5809b-f8a1-428b-87c3-fc980593b4dc",
            "date": "2019-07-15T06:46:16"
        }
    }
}

**Comment by RamjotSingh** [comment] 2019-07-17 07:06
@adrichema It looks the user does not have access to Team. Are you certain the user is present on the team? Can you open teams client and check. If the user gets synced on Teams client (added to the list of members/owners based on your team settings). Try the operation again and see if it succeeds. At the moment it looks like the user is not authorized to perform the operation.

**Comment by adrichema** [comment] 2019-07-17 07:41
@RamjotSingh The channels are created using a "Provisioning User" is an owner of the actual group (and team). This user also created the team.

{
  "@odata.type": "#microsoft.graph.user",
  "id": "e7bd1255-e686-4cfd-863f-d609468f6afa",
   "userPrincipalName": "one-provisioning-user@ourdomain.onmicrosoft.com"
 },

The tests using Graph Explorer are done by a Office 365 Admin. I just found out that creating a team via de Team Admin Center gives an error as well. Is the Admin Center using the Graph API or does it talk directly to the Skype backend?

**Comment by RamjotSingh** [comment] 2019-07-17 17:40
@adrichema I think there is a discrepancy here. Are the request being made on behalf of a user or in application context? If it is the former, I see the request being made on behalf of user with Id 1f79c2ff-60df-42fb-b738-160004719b0c

**Comment by adrichema** [comment] 2019-07-17 18:27
@RamjotSingh That is indeed very strange. This is the user (Kamal) is the first owner of the team. I don't even have the credentials of this user.

For the calls made using the Graph Explorer I am using the user with Id  c496b43a-4a0f-4c9b-b940-7cc8cb5cfb9a. When I do a Get on the /me/ endpoint I am getting the following result.
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users/$entity",
    "displayName": "Admin CompanyName",
    "givenName": "Admin",
    "jobTitle": null,
    "mail": "admin@ourdomain.onmicrosoft.com",
    "mobilePhone": null,
    "officeLocation": null,
    "preferredLanguage": "nl-NL",
    "surname": CompanyName",
    "userPrincipalName": "admin@ourdomain.onmicrosoft.com",
    "id": "c496b43a-4a0f-4c9b-b940-7cc8cb5cfb9a"
}

I am pretty sure the Graph Explorer does not use a application context when creating a team of channel. Could you confirm this?

**Comment by RamjotSingh** [comment] 2019-07-18 06:14
Graph Explorer works with the Id of the user which is logged in. Is the user you are using Tenant Administrator? That might explain a few things.

**Comment by adrichema** [comment] 2019-07-18 06:20
@RamjotSingh, yes the user Admin CompanyName is a tenant administrator.

**Comment by RamjotSingh** [comment] 2019-07-18 06:23
@adrichema And the TenantAdministrator is also the owner of the team or not?

**Comment by adrichema** [comment] 2019-07-18 06:32
@RamjotSingh, no the tenant administrator is not an owner of the team. But the provisioning user "one-provisioning-user@ourdomain.onmicrosoft.com" is. This is the account that we normally use for creating teams and channels is a owner. Both fail, both using delegated permissions. 

I just logged on with the one-provisioning-user on the Graph Explorer and tried to create a channel. It failed with the following error:

{
    "error": {
        "code": "AccessDenied",
        "message": "Unable to fetch team thread: Failed to execute Skype backend request GetThreadS2SRequest.",
        "innerError": {
            "request-id": "bcb5537e-48da-496b-ac86-0e7e5a288a40",
            "date": "2019-07-18T06:30:54"
        }
    }
}

**Comment by RamjotSingh** [comment] 2019-07-18 06:37
@adrichema I think I have enough info. Let me engage the team owning that API. This might require a rather deep look into why it is failing.

**Comment by ericrrichards** [comment] 2019-08-01 18:04
As another data point, I get this GetThreadS2SRequest error intermittently from the Graph API when I am attempting to list the Channels of a team, e.g. GET https://graph.microsoft.com/v1.0/teams/{teamid}/channels

I haven't been able to determine any kind of pattern for why it fails - there's no team id where this request will consistently fail, and some requests will succeed, and then the next request will fail.

It kind of looks like typical Skype for Business backend instability and gremlins.

**Comment by czullu** [comment] 2019-08-26 06:21
i'm having this issue as well on one of our tenants. The first one is from a Team created by Code
{
    "error": {
        "code": "AccessDenied",
        "message": "Failed to execute Skype backend request GetThreadsS2SRequest.",
        "innerError": {
            "request-id": "81285b72-a52c-49aa-869c-a862d822725d",
            "date": "2019-08-26T06:12:15"
        }
    }
}

This one is from a team created by MS UI in Teams.
{
    "error": {
        "code": "AccessDenied",
        "message": "Failed to execute Skype backend request GetThreadsS2SRequest.",
        "innerError": {
            "request-id": "d749f9b2-11e2-4072-8cf7-ace601a65bee",
            "date": "2019-08-26T06:20:20"
        }
    }
}

**Comment by kkabza** [comment] 2019-08-26 23:00
Ditto!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Trinetra-MSFT** [comment] 2019-08-27 08:43
Could you please test it again? Let us know if you are still facing this issue.

**Comment by czullu** [comment] 2019-08-28 06:13
I can confirm that it's working on our different tenants again. Thanks for fixing.

**Comment by adrichema** [comment] 2019-08-28 12:29
Looks like the issue has been fixed. I would like to know what was causing the issue? Also why it did take so long to fix it (almost 2 months).

**Comment by Prasanthi99** [comment] 2020-04-17 13:17
I'm also facing the same issue while fetching channels of a team. For some users it's working fine. 
I got this error:
{
    "error": {
        "code": "BadRequest",
        "message": "Failed to execute Skype backend request GetThreadS2SRequest.",
        "innerError": {
            "request-id": "20d9de3b-bcdc-480e-bcea-951caf620514",
            "date": "2020-04-17T13:02:35"
        }
    }
}

Can anyone

**Comment by ashoksubedi1** [comment] 2020-04-17 17:15
yeap, started getting this error from yesterday
https://graph.microsoft.com/v1.0/teams/0ccfb*******c-bebd-0*****ee1d

{
    "error": {
        "code": "BadRequest",
        "message": "Failed to execute Skype backend request GetThreadS2SRequest.",
        "innerError": {
            "request-id": "78ffa8eb-257c-46c8-93c3-5c2a02e494e4",
            "date": "2020-04-17T17:14:18"
        }
    }
}

**Comment by czullu** [comment] 2020-04-17 17:34
@ashoksubedi1 Same on my end - checked for 3 tenants - it's all the same. This message often means that a certificate is expired... so please microsoft

**Comment by ahouck** [comment] 2020-04-17 18:02
I am also getting this issue trying to list channels of a team I am a member of. I've been using the same plain requests in the graph explorer to test with for the past month. Just started to get this error all of a sudden.

**Comment by ksikorsk** [comment] 2020-04-17 18:17
I can't find any of the `AccessDenied` errors in our logs.  This is likely failing authentication before it even reaches graph.  @darrelmiller how do we normally verify if the issue is with fetching a token?

There is one 400 - BadRequest in the mix, which I was able to get the logs for. 
 @ashoksubedi1 

Looks like teams is returning this, and is usually a signal of a malformed request.  I am not familiar with this API, someone on teams side will have to help you here.  @nkramer?

For internal use:
https://msgraphlogs.azurewebsites.net/?useUTC=true&dateTime=2020-04-17T17%3A14%3A18.4768761&offsetUnits=Minutes&offsetDuration=15&offsetDirection=%C2%B1&requestId=78ffa8eb-257c-46c8-93c3-5c2a02e494e4&env=MSODS

**Comment by kkabza** [comment] 2020-04-17 18:23
I can see this issue in the core major incidents channel. There is a Sev 1 incident already raised.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ahouck** [comment] 2020-04-17 19:10
@kkabza  Where do you find the incidents channel?

**Comment by ashoksubedi1** [comment] 2020-04-17 20:40
@ksikorsk hi there, do you have any idea how i can resolve this issue, my app creating groups and all but right when it is time to create a team I get an error
https://graph.microsoft.com/v1.0/groups/0*******b7a7-0a931544db69/team PUT request

{
    "error": {
        "code": "BadGateway",
        "message": "Failed to execute backend request.",
        "innerError": {
            "request-id": "2ab31a91-1093-4b2b-a570-9eb23b36519f",
            "date": "2020-04-17T20:23:48"
        }
    }
}

**Comment by yangchristian** [comment] 2020-04-17 21:15
@ahouck think the incidents/service status page is here in the admin UI: https://portal.office.com/Adminportal/Home#/servicehealth

**Comment by ashoksubedi1** [comment] 2020-04-17 21:33
@ahouck and @yangchristian  This is what I found on my incident page for teams

Title: Administrators unable to perform certain functions in the Microsoft Teams admin center

User Impact: Admins are unable to manage Teams and Channels through the Microsoft Teams admin portal.

More info: Impacted functionality within the Teams admin center would include:
- Teams information will be grayed out and admins will not be able to manage Teams.
- Admins will not be able to use cmdlets to manage Teams.
- Admins would be unable to create new schedules in the “Shifts” application.

Teams owners can still create, manage, and delete Teams and Channels, as well as update Shifts information.

Current status: We've identified a code regression within the Teams infrastructure, which is preventing some functions within the Microsoft Teams admin portal from working as expected. We're deploying a fix across the affected infrastructure to mitigate impact.

Scope of impact: Administrators trying to manage Teams and Channels through the Teams admin portal.

Start time: Friday, April 17, 2020, 4:00 AM (11:00 AM UTC)

Estimated time to resolve: The deployment is expected to complete within the next 2 days.

Root cause: A code regression within the Teams infrastructure is causing some functions within the Microsoft Teams admin portal to not work as expected.

Next update by: Sunday, April 19, 2020, 3:00 AM (10:00 AM UTC)

**Comment by micromega-prog** [comment] 2020-05-05 01:59
We've been seeing this issue for a few days now.

When trying to get the channels for some existing Teams we receive the following error:

Invoke-RestMethod : {
  "error": {
    "code": "Forbidden",
    "message": "Failed to execute Skype backend request GetThreadS2SRequest.",
    "innerError": {
      "request-id": "12fad693-9062-4fc8-9384-37ab3ed99400",
      "date": "2020-05-05T01:48:59"
    }
  }
}
At line:2 char:13
+ $channels = Invoke-RestMethod -Headers @{Authorization = "Bearer $($T ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

We're connecting to the Graph api using delegated authentication in this case. This also only appears to affect some Teams.

**Comment by rajesh-rajanS** [comment] 2020-07-30 08:23
Is this issue fixed? I am still facing the issue in getting ms teams channels only for non-admin users
`https://graph.microsoft.com/v1.0/teams/team_id/channels`
{
    error: {
       code: 'Forbidden', 
       message: 'Failed to execute Skype backend request GetThreadRequest.',
       innerError: {
         date: '2020-07-29T21:09:30',
         'request-id': '3c6e8d8a-fdff-433b-877e-c785690837f5'
       }
    }
}

Provided the right application permissions and granted admin consent.

**Comment by rajesh-rajanS** [comment] 2020-07-30 09:58
Is this issue fixed? I am still facing the issue in getting ms teams channels only for non-admin users
`https://graph.microsoft.com/v1.0/teams/team_id/channels`
```
{
    error: {
       code: 'Forbidden', 
       message: 'Failed to execute Skype backend request GetThreadRequest.',
       innerError: {
         date: '2020-07-29T21:09:30',
         'request-id': '3c6e8d8a-fdff-433b-877e-c785690837f5'
       }
    }
}
```

Provided the right delegated permissions `Group.ReadWrite.all` and `Directory.Read.all `permissions and granted admin consent.

**Comment by RamjotSingh** [comment] 2020-07-30 11:55
Forbidden means the user does not have access to the team.

**Comment by RamjotSingh** [comment] 2020-07-30 11:56
Closing this since the original issue was solved and now this thread is being used for tracking other issues. Please open new issue for any issues you face.

**Comment by RamjotSingh** [comment] 2020-07-30 11:57
#please-close

**Comment by rajesh-rajanS** [comment] 2020-07-30 13:00
okay. where can I create a new issue?

**Comment by RamjotSingh** [comment] 2020-07-30 19:53
There is a Issues option under the documentation page.

**Comment by MIchaelMainer** [comment] 2021-05-06 17:31
Original issue has been addressed.

**Closed by MIchaelMainer** 2021-05-06 17:31 UTC
Labels: Needs: Attention :wave:, promote, service bug
