### ISSUE TITLE
[Client bug]: Error updating app registration with GB18030 character

### ISSUE THREAD

**Issue by zahalzel** [microsoftgraph/msgraph-sdk-dotnet#2039] opened 2023-07-26 19:38 UTC
**Describe the bug**
Creating an app registration and publishing to Azure, the URL of the published site contains a GB18030 character
https://xn--msi20230725123842-o72vta.azurewebsites.net

Using the GraphServiceClient SDK to update an app registration with the following redirect URI:
 I am attempting to run PatchAsync() to update a Microsoft.Graph.Models.Application object. 
The code looks like this: 

`var updatedApp = await graphServiceClient.Applications[remoteApp.Id].
    PatchAsync(appUpdates)`

where appUpdates is a `Microsoft.Graph.Models.Application` object, the field causing the error is this string:
`"https://xn--msi20230725123842-o72vta.azurewebsites.net/signin-oidc"`

which we want to add to the `Application.Web.RedirectUris` list

This call ends up throwing a `Microsoft.Graph.Models.ODataErrors.ODataError` exception, "One or more properties contains invalid values"

Related bug in Azure DevOps: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1860249/

**Screenshots**
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/75647613/7d227bfe-f906-473e-a0ab-3cf2305eeef9)

**Client version**
Microsoft.Graph 5.25.0

**Comment by andrueastman** [comment] 2023-07-27 08:26
Thanks for raising this @zahalzel 

Any chance you are able to share the other properties from the `ServiceException` i.e the request-id code and message to help understand the issue better?

**Comment by zahalzel** [comment] 2023-07-28 19:20
@andrueastman Here is the full exception: 
Microsoft.Graph.ServiceException
{"Code: Request_BadRequest\r\nMessage: One or more properties contains invalid values.\r\nInner error:\r\n\tAdditionalData:\r\n\tdate: 2023-07-28T19:15:08\r\n\trequest-id: afa39607-09c8-496c-b006-a0173f7fbc89\r\n\tclient-request-id: afa39607-09c8-496c-b006-a0173f7fbc89\r\nClientRequestId: afa39607-09c8-496c-b006-a0173f7fbc89\r\n"}

**Comment by bribrothers** [comment] 2023-09-06 18:06
@andrueastman any updates on this one?

**Comment by bribrothers** [comment] 2023-09-13 19:50
@andrueastman this is currently a compliance issue for VS, do you have an update?

**Comment by zahalzel** [comment] 2023-09-28 18:15
@andrueastman Some more context on this, I am attempting to run PatchAsync() to update a Microsoft.Graph.Models.Application object. 
The code looks like this: 

`var updatedApp = await graphServiceClient.Applications[remoteApp.Id].
    PatchAsync(appUpdates)`

where appUpdates is a Microsoft.Graph.Models.Application object.

The specific field that is causing an issue is the RedirectUris list, found in the Microsoft.Graph.Models.WebApplication here: https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/4c556b91c40bd1ff87500ce2916ade3ef11a79ed/src/Microsoft.Graph/Generated/Models/WebApplication.cs#L76

The element included in the list of RedirectUris is this: `"https://xn--msi20230928124403-o72vta.azurewebsites.net/signin-oidc"`

And the resulting exception is a Microsoft.Graph.Models.ODataErrors.ODataError, the Error message is as follows:
"One or more properties contains invalid values."

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/75647613/7d227bfe-f906-473e-a0ab-3cf2305eeef9)

**Comment by andrueastman** [comment] 2023-10-02 09:13
Following up via https://portal.microsofticm.com/imp/v3/incidents/details/428378536/home

**Comment by andrueastman** [comment] 2023-11-08 09:32
Closing this for now as the feedback is that the error is by design from the API side.

**Closed by andrueastman** 2023-11-08 09:32 UTC
Labels: Service issue, Status: Under investigation
