### ISSUE TITLE
V5 Create Team doesn't return a result

### ISSUE THREAD

**Issue by idealser** [microsoftgraph/msgraph-sdk-dotnet#1798] opened 2023-03-31 14:28 UTC
Create Team is an async operation and it won't return any result other than url of the operation. In V5 GraphClient.Teams.PostAsync has a Team object as a return result, but at runtime it actually returns you null. This leads to total confusion. I guess it shouldn't return you anything if you can't rely on the result like the same way it's implemented with Clone.

Instead of this it's better to drop the return result and add to the documentation sample on how to corectly get the execution result object.

**Comment by andrueastman** [comment] 2023-04-03 09:03
Thanks for raising this @idealser 

As this is dependent on the generated metadata, we'll close this as a duplicate of https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1366 as this is dependent on https://github.com/microsoftgraph/msgraph-sdk-design/issues/83

**Closed by andrueastman** 2023-04-03 09:03 UTC
Labels: duplicate
