### ISSUE TITLE
Enable Sourcelink on Package

### ISSUE THREAD

**Issue by michael-hawker** [microsoftgraph/msgraph-sdk-dotnet#747] opened 2020-07-23 22:19 UTC
![image](https://user-images.githubusercontent.com/24302614/88344161-dc1b8180-ccf7-11ea-92a3-1c7c00744b03.png)

**Describe the bug**
Sourcelink/Symbols is not enabled on the package which makes it harder to debug issues with the SDK.

**Expected behavior**
Sourcelink should be enabled.

**Comment by ddyett** [comment] 2020-08-03 21:08
Closing this as duplicate of https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/133 .  We are tracking this for all packages.

**Comment by zengin** [comment] 2021-03-25 02:19
reopening to represent repo specific fix.

**Closed** 2021-03-25 16:40 UTC
