### ISSUE TITLE
BUG in ScheduleRequest.UpdateAsync method

### ISSUE THREAD

**Issue by leonardospina** [microsoftgraph/msgraph-sdk-dotnet#963] opened 2021-04-15 08:55 UTC
**Describe the bug**
ScheduleRequest.UpdateAsync invokes the API doing a PATCH request, while the Graph Api expects a PUT request, hence a 404 error is returned

**To Reproduce**
1. Use Graph Explorer: https://developer.microsoft.com/en-us/graph/graph-explorer
2. Insert the API url https://graph.microsoft.com/v1.0/teams/{teamid}/schedule (replace placeholder with a valid TeamId you have access to)
3. Select PATCH as verb
4. Use a valid Schedule Json as request body :
`{
    "enabled": true,
    "timeZone": "Europe/Dublin",
    "provisionStatus": "Completed",
    "provisionStatusCode": null,
    "workforceIntegrationIds": [],
    "timeClockEnabled": false,
    "openShiftsEnabled": true,
    "swapShiftsRequestsEnabled": true,
    "offerShiftRequestsEnabled": true,
    "timeOffRequestsEnabled": true
}`
5. Run the query
6. An EMPTY HTTP 204 response is returned

**Expected behavior**
HTTP 200 + a Schedule object should be returned
![image](https://user-images.githubusercontent.com/11229315/114864334-c51e4180-9de8-11eb-9239-3b1d0ccd3ac5.png)

**Screenshots**
Example with PATCH request (Error 404 is returned):
![image](https://user-images.githubusercontent.com/11229315/114841188-787a3c80-9dcf-11eb-99f3-b94f958af3c6.png)

Example with PUT request (204 is returned):
![image](https://user-images.githubusercontent.com/11229315/114841302-95af0b00-9dcf-11eb-9100-b0737f9c70b9.png)

**Desktop (please complete the following information):**
 - OS: Windoes 10 Pro
 - Browser MS Edge
 - Version 89.0.774.76 (Official build) (64-bit)

**Additional context**
![image](https://user-images.githubusercontent.com/11229315/114841883-39002000-9dd0-11eb-993c-3ffe1a723402.png)

![image](https://user-images.githubusercontent.com/11229315/114842130-78c70780-9dd0-11eb-8540-9c41517fb8e6.png)
 
[AB#9004](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9004)

**Comment by leonardospina** [comment] 2021-04-15 09:28
Not as relevant as the main issue from a functional point of view, but I noticed these two block of code that are identical, one should be removed:

![image](https://user-images.githubusercontent.com/11229315/114847168-51bf0480-9dd5-11eb-8f40-0059c405a338.png)

**Comment by andrueastman** [comment] 2021-04-22 09:34
@leonardospina Thanks for raising this issue. We are currently working on an updated major version of the sdk which is still in preview. More info [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/935).
If you are willing to try it out, the issue is now resolved via the addition of `PutAsync` methods for entities. You should therefore be able to make a call like this using the sdk.

```
await graphClient.Teams[""].Schedule.Request().PutAsync(scheduleToUpdate);
```

**Closed by andrueastman** 2021-04-22 09:34 UTC
