### ISSUE TITLE
ReferenceCreate is not part of deviceManagement/managedDevices/{managedDevice-id}/deviceCategory

### ISSUE THREAD

**Issue by dansmitt** [microsoftgraph/msgraph-sdk-dotnet#2503] opened 2024-05-21 08:28 UTC
### Describe the bug

We want to set the ``DeviceCategory`` of a ``ManagedDevice``. So Intune already calls this endpoint:
[https://graph.microsoft.com/v1.0/deviceManagement/managedDevices/{managedDevice-id}/deviceCategory/$ref](https://graph.microsoft.com/v1.0/deviceManagement/managedDevices/%7BmanagedDevice-id%7D/deviceCategory/$ref)

Ref is not part of in the SDK so far.

### Expected behavior

Ref is part for the ``deviceManagement/managedDevices/{managedDevice-id}/deviceCategory`` endpoint in the SDK like ``deviceManagement/managedDevices/{managedDevice-id}/deviceCategory/$ref``

### How to reproduce

Just try to use the ref attribute in the SDK for the call

### SDK Version

5,x

**Comment by andrueastman** [comment] 2024-06-03 10:05
Thanks for raising this @dansmitt 

We'll close this once https://github.com/microsoftgraph/msgraph-metadata/issues/633 is resolved as this looks to be caused by a missing path in the input metadata.

**Closed** 2024-10-08 06:33 UTC
Labels: Bug: metadata, type:bug
