### ISSUE TITLE
Wrong C# code snippets for Directory Role APIs - Remove member

### ISSUE THREAD

**Issue by FaithOmbongi** [microsoftgraph/msgraph-sdk-dotnet#1042] opened 2021-06-18 15:38 UTC
Hello,

To resolve customer issue [#13018](https://github.com/microsoftgraph/microsoft-graph-docs/issues/13018), I raised a PR to request new code snippets but the issue persists in the new code snippets. This issue applies only to the C# snippets where the request uses the **roleTemplateId** instead of directoryRole **id**.

**Current snippet**
From [Remove member: Example 2 (v1.0)](https://docs.microsoft.com/en-us/graph/api/directoryrole-delete-member?view=graph-rest-1.0&tabs=csharp#example-2-remove-directory-role-member-using-role-templateid), [Example 2 (beta)](https://docs.microsoft.com/en-us/graph/api/directoryrole-delete-member?view=graph-rest-beta&tabs=csharp#example-2-remove-directory-role-member-using-role-templateid)
```C#
GraphServiceClient graphClient = new GraphServiceClient( authProvider );

await graphClient.DirectoryRoles["{directoryRole-id}"].Members["{directoryObject-id}"].Reference
	.Request()
	.DeleteAsync();
```

**Expected behavior** (as extracted from Graph Explorer)
```c#
GraphServiceClient graphClient = new GraphServiceClient( authProvider );

await graphClient.DirectoryRoles["roleTemplateId=9f06204d-73c1-4d4c-880a-6edb90606fd8"].Members["bb165b45-151c-4cf6-9911-cd7188912848"]
	.Request()
	.DeleteAsync();
```

**Additional context**
- Related issues: #1041 , #1043 
- PR to request new code snippets: https://github.com/microsoftgraph/microsoft-graph-docs/pull/13026
- Affects only C#. 
[AB#9957](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9957)

**Comment by andrueastman** [comment] 2021-06-29 14:37
This seems to be the intended behavior to enable testing and validation of the snippets as the snippets in the docs need to have placeholder values to enable execution tests to ensure their correctness. See [here](https://github.com/microsoftgraph/microsoft-graph-devx-api/blob/dev/CodeSnippetsReflection/LanguageGenerators/CSharpGenerator.cs#L341)

Graph Explorer users will not see this behavior and this change is expected to propagate to other languages as the snippet validation is implemented in those languages as well. 

Closing this for now.

**Closed by andrueastman** 2021-06-29 14:37 UTC
