### ISSUE TITLE
Regression: /me/photo no longer returns an MSA's profile picture

### ISSUE THREAD

**Issue by mfeingol** [microsoftgraph/msgraph-sdk-dotnet#568] opened 2019-10-28 05:09 UTC
**Describe the bug**

It looks like /me/photo has stopped working for MSA profile pictures.

The error returned by the API is along the lines of:

```
{
    "error": {
        "code": "ConsumerPhotoIsNotSupported",
        "message": "The photo wasn't found.",
        "innerError": {
            "request-id": "fd56c8a9-07b5-4627-9e98-ff5868611f2a",
            "date": "2019-10-27T01:28:50"
        }
    }
}
```

This used to work. It appears to have recently stopped working.

I verified that it works for an AAD "work" account, so the issue appears to be only with MSAs. I tested two different MSAs, both with valid profile pictures.

**To Reproduce**

The repro is simple:

1. Sign into https://account.microsoft.com/ with an MSA, ensure a profile picture is set
2. With that same MSA, sign into https://developer.microsoft.com/en-us/graph/graph-explorer
3. Query on https://graph.microsoft.com/v1.0/me/photo/ or https://graph.microsoft.com/beta/me/photo/
4. Observe the 404 failure

**Expected behavior**

Return the profile picture on the MSA. 
[AB#7304](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7304)

**Comment by mfeingol** [comment] 2019-11-07 06:00
Hi.

Any updates on the investigation of this issue?

Thanks.

**Comment by MIchaelMainer** [comment] 2019-11-12 16:41
@svpsiva Is this a new behavior for this API with MSA?

**Comment by LaurentTermeau** [comment] 2019-11-19 23:31
I've personally not used it until I discovered this limitation. According to the post from @mfeingol above it used to work in the past, that's why he qualifies this as a regretion.
If it is a known limitation of the Microsoft graph api, then I would love to have a suggested alternative that works. For now, the only think I've been doing is displaying a colored circle with user's initials in it... Not very personalized experience!

**Comment by mfeingol** [comment] 2019-11-19 23:36
I'm not sure when it stopped working, but it's been working since at least 2017.

**Comment by kevinbellinger** [comment] 2019-11-20 10:27
We're looking into this - it appears to be related to a cross-system dependency which broke at some point recently. We hope to have it back and available in Beta in the coming weeks. Apologies for the inconvenience here.

**Comment by srnitk** [comment] 2019-12-25 05:37
When are we getting this fixed? One of our features has stopped working. It's been more than a month. If there is any workaround, please do share.

**Comment by ArunGitBackup** [comment] 2020-01-28 14:22
Is the issue fixed yet?

Any updates on this issue?

Thanks/.

**Comment by srnitk** [comment] 2020-01-30 13:50
Any updates on this?

Thanks!!

**Comment by kevinbellinger** [comment] 2020-01-31 05:11
It's working now.

**Comment by stubclan** [comment] 2020-01-31 17:27
@kevinbellinger Its still not working for me. I just checked it right now on Graph Explorer.
Anything I should do to make it work?

**Comment by kevinbellinger** [comment] 2020-02-01 04:40
It's only supported on Beta - not V1. It never worked on V1. (we're working on enabling that capability with a new API in V1)

**Comment by yunyuyuan** [comment] 2020-02-03 07:22
@kevinbellinger Thank for your working,We await your resolve.

**Comment by DarkHack** [comment] 2020-03-05 14:53
@kevinbellinger not V1? to be V1 or not?
how can we explain, graph V1 in debug work, and in context, crash...
cause V1 never work, only in debug developer graph ?

![V1_workongraph_notcontext](https://user-images.githubusercontent.com/1688072/75993148-57bb9400-5ef9-11ea-8b26-23937fd5ba5b.jpg)

**Comment by MarcoEnxuto** [comment] 2021-01-02 20:04
Hi, this is still on track? I see this is closed, but looks like the API still has the issue. @kevinbellinger any news?

**Comment by MarcoEnxuto** [comment] 2021-03-04 23:20
Hello, is this still in progress? I do see it returns 404. I guess people have to ship their software using the beta endpoint which is the one that currently works.

**Comment by eanders-MS** [comment] 2021-03-10 07:37
@kevinbellinger can you suggest a workaround until the issue is resolved? What is the beta endpoint?

Thanks for keeping this open in the meantime.

**Comment by MarcoEnxuto** [comment] 2021-03-10 09:08
> @kevinbellinger can you suggest a workaround until the issue is resolved? What is the beta endpoint?
> 
> Thanks for keeping this open in the meantime.

Hi @eanders-MS, this one: https://graph.microsoft.com/beta

**Comment by kevinbellinger** [comment] 2021-03-12 17:16
We just shipped the new underlying endpoint to beta last week. We're giving it a short period of time and then will go to V1 where consumer photos will be finally supported. 

To add context for the delay, we came across some inconsistencies when rolling the endpoint to Beta the first time which we wanted to fix before rolling out more broadly. 

We know this has been a long journey and really appreciate the patience!

**Comment by MarcoEnxuto** [comment] 2021-03-13 21:11
> We just shipped the new underlying endpoint to beta last week. We're giving it a short period of time and then will go to V1 where consumer photos will be finally supported.
> 
> To add context for the delay, we came across some inconsistencies when rolling the endpoint to Beta the first time which we wanted to fix before rolling out more broadly.
> 
> We know this has been a long journey and really appreciate the patience!

Thank you @kevinbellinger . Let us know when it goes to v1 and then close this issue.

**Comment by andrueastman** [comment] 2021-05-19 14:26
@kevinbellinger Any updates on when this will move to v1.0?

**Comment by MarcoEnxuto** [comment] 2021-05-19 15:57
> @kevinbellinger Any updates on when this will move to v1.0?

Just checked the Production endpoint v1 and is still returning the error. Cannot get the profile picture.

**Comment by MarcoEnxuto** [comment] 2021-08-19 08:35
Hi, as of now, we still don't get the profile picture with the current production endpoint. I'm forced to use the beta route.

**Comment by maisarissi** [comment] 2022-01-19 21:08
Hello everyone.

Per @kevinbellinger comment above, the functionality is supported on beta endpoint (https://graph.microsoft.com/beta/) and at some point, it will also be available on v1. 
If the feature is not yet supported on v1, I suggest you all to request it (or upvote if the request is already there) in the [Microsoft Q&A](https://aka.ms/graphrequests) and tagged with [microsoft-graph-users](https://docs.microsoft.com/en-us/answers/search.html?c=&includeChildren=&f=&type=question+OR+idea+OR+kbentry+OR+answer+OR+topic+OR+user&redirect=search%2Fsearch&sort=relevance&q=microsoft-graph-users) tag.

Thank you for reporting this issue. As pointed out before, this is an issue with the service API and this repository is specific to the .NET client library. So, I'm closing this issue.

**Closed by maisarissi** 2022-01-19 21:08 UTC
Labels: service bug, promote
