### ISSUE TITLE
Occassional Microsoft.Graph error: Received an invalid status line: '0'

### ISSUE THREAD

**Issue by yogigrantz** [microsoftgraph/msgraph-sdk-dotnet#1837] opened 2023-04-18 18:04 UTC
I have a function to delete emails from a mailbox, and it is coded like this:

`static async Task DeleteEmails(GraphServiceClient graphClient, int maxNbrOfEmails, string mailbox)
{
    MessageCollectionResponse? messages = await graphClient.Me.MailFolders[mailbox].Messages.GetAsync(x => { x.QueryParameters.Top = maxNbrOfEmails; });

    if (messages?.Value.Count > 0)
    {
        int i = 0;
        foreach (Message m in messages.Value)
        {
            i++;
            Console.WriteLine($"Deleting {m.ReceivedDateTime} - {m.Sender.EmailAddress.Address} - {m.Subject} ");
            
            try
            {
                await graphClient.Me.MailFolders[mailbox].Messages[m.Id].DeleteAsync();
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error deleting email #{i} {m.Id} {m.ReceivedDateTime} {m.Subject} {ex.Message}");
            }
        }
    }
}`

The DeleteAsync() works 95% of the time. Typical situation is that out of 1000 emails, it would delete 967 of them. At random emails it would go to the catch section and report the failures. But if I run the function again, it would pick up the emails that were not deleted previously and deleted most or all of them if the number of emails is small enough. 

Eventually if I run this program often enough, it would delete all the emails. But my question is, what would randomly caused "Received an invalid status line: '0'" error?

Sample usage of this function:

`IAuthenticationProvider cap = new ConsoleAppAuthenticationProvider(new OAuth2DTO()
{
    ClientId = "****",
    TenantId = "****",
    UserName = ****,
    Password = "****"
}, @"C:\Temp\GraphCache.txt");

// Pass auth provider to the new instance of graphClient
GraphServiceClient graphClient = new GraphServiceClient(cap);

int maxNbrOfEmails = 1000;
string[] scopes = new[] { "Mail.ReadWrite" };

await DeleteEmails(graphClient, maxNbrOfEmails, "INBOX");
`

where OAuth2DTO is a DTO containing ClientId, TenantId, Username, and Password, and ConsoleAppAuthenticationProvider is a class that inherits from IAuthenticationProvider, which stores and retrieve the bearer token to / from the text file and furnish the request header with the bearer token request.Headers.Add("Authorization", "Bearer " + this.accessToken);  

could this issue have come from Microsoft.Kiota.Abstractions.SendAsync ?

**Comment by yogigrantz** [comment] 2023-04-18 18:48
I uploaded my full solution of the Microsoft.Graph Test program here: https://github.com/yogigrantz/MicrosoftGraphTest . It does require valid ClientId, TenantId, Username, Password, and Azure App Registrtion and cope permissions

**Comment by andrueastman** [comment] 2023-04-20 09:53
Thanks for raising this @yogigrantz 

I notice that this line is not surrounded by a try catch block and could possible fail/timeout given the large number of emails requested in once request. Any chance you could first try that and see if this is the error to try to uncover more details?

https://github.com/yogigrantz/MicrosoftGraphTest/blob/7c8a459f7418ee13edd9fbf24e7eb392d786f32a/EmailConceptG/Program.cs#L69

**Comment by yogigrantz** [comment] 2023-04-20 21:27
Hello @andrueastman  , thank you for looking into this issue 

Line 69 MessageCollectionResponse? messages = await graphClient.Me.MailFolders[mailbox].Messages.GetAsync(x => { x.QueryParameters.Top = maxNbrOfEmails; }); 

was never a problem. Even if I surround it with try catch block it would not error out for me. The error actually occurred in line 81: 

 await graphClient.Me.MailFolders[mailbox].Messages[m.Id].DeleteAsync(); 

and it fell to the catch section where it displays the error in line 85 (and this happens randomly, less than 5% of the time):

Console.WriteLine($"Error deleting email #{i} {m.Id} {m.ReceivedDateTime} {m.Subject} {ex.Message}"); 

When looking at Microsoft.Graph source code, it looks like the exception error came from this statement (if I'm not mistaken):

 await RequestAdapter.SendNoContentAsync(requestInfo, errorMapping, cancellationToken); 

inside DeleteAsync function in MailFolders.Item.Messages.Item.Extensions.Item.ExtensionItemRequestBuilder.cs ,which is pointing to Microsoft.Kiota.Abstraction.SendNoContentsAsync

**Comment by andrueastman** [comment] 2023-04-25 06:53
Any chance you can modify the exception block to match the error handling in the documentation at the link below and share the details?
 
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#error-handling

**Comment by yogigrantz** [comment] 2023-04-26 16:26
Here is the error log from our production run at 9am this morning, where it deleted 46 out of 47 emails: 

[2023-04-26 09:00:23]   - SentItems: Email Delete Error. Email #20: Sender: *****. Recipients *******. Subject: Resume Received!  -  . Sent/Received: 4/26/2023 3:51:05 PM +00:00 | Error Source - message: System.Net.Http - Received an invalid status line: '0'.
-------------------
[2023-04-26 09:00:23]   - SentItems: 47 emails found, 46 Deleted

**Comment by andrueastman** [comment] 2023-04-27 08:06
I was mainly referring to printing out the error log as described in the link above. 
However, it looks like the error may be caused by the service returning an invalid HTTP response which may not provide enough error information. 

Out of curiosity, do you still get errors if you batch the requests in payloads, by doing something like this?

https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#batch-requests

```cs
            MessageCollectionResponse? messages = await graphClient.Me.MailFolders[mailbox].Messages.GetAsync(x => { x.QueryParameters.Top = 30; });

            var batchRequestContent = new BatchRequestContentCollection(graphClient);
            if (messages?.Value.Count > 0)
            {
                foreach (Message m in messages.Value)
                {
                    var requestInformation = graphClient.Me.MailFolders[mailbox].Messages[m.Id].ToDeleteRequestInformation();
                    await batchRequestContent.AddBatchRequestStepAsync(requestInformation);
                }

                // Batch the message deletions
                var batchResponseContent = await graphClient.Batch.PostAsync(batchRequestContent);

                var statusCodes = await batchResponseContent.GetResponsesStatusCodesAsync();

                // all the responses are successfull?
                var nonSuccessfulResponses = statusCodes.Where(x => !BatchResponseContent.IsSuccessStatusCode(x.Value));

                Console.WriteLine($"Failed request count: {nonSuccessfulResponses.Count()}");
            }
```

**Comment by yogigrantz** [comment] 2023-04-27 20:23
Hi @andrueastman  : This is a much better implementation. I didn't know .Batch.PostAsync existed. It looks like it is deleting all the emails when I posted a batch request. The number found and the number deleted are equal now. Will keep an eye on this application. Thank you so much for helping, you're awesome!

Here is my log:

```
[2023-04-27 13:13:59]   - ---- Email Delete summary for *****@*****.com ----
-------------------
[2023-04-27 13:13:59]   - INBOX: 6 emails found, 6 Deleted
-------------------
[2023-04-27 13:13:59]   - DeletedItems: 0 emails found, 0 Deleted
-------------------
[2023-04-27 13:13:59]   - SentItems: 269 emails found, 269 Deleted
-------------------
[2023-04-27 13:14:07]   - ---- Email Delete summary for *****@*****.com ----
-------------------
[2023-04-27 13:14:07]   - INBOX: 0 emails found, 0 Deleted
-------------------
[2023-04-27 13:14:07]   - DeletedItems: 0 emails found, 0 Deleted
-------------------
[2023-04-27 13:14:07]   - SentItems: 110 emails found, 110 Deleted

```

**Comment by andrueastman** [comment] 2023-04-28 06:56
Thanks for the feedback here @yogigrantz 

We'll close this for now. Feel free to re-open incase of any issues.

**Closed by andrueastman** 2023-04-28 06:56 UTC
Labels: Needs: Attention :wave:
