### ISSUE TITLE
How to update hiredate and birthday using Graph .NET SDK

### ISSUE THREAD

**Issue by miguelisidoro** [microsoftgraph/msgraph-sdk-dotnet#1316] opened 2022-04-15 22:09 UTC
Hello,

I am building an Azure function to update birthday and hiredate in Azure AD based on data in a SharePoint List.

According to https://docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&tabs=http:
• The following properties cannot be updated by an app with only application permissions: aboutMe, birthday, employeeHireDate, interests, mySite, pastProjects, preferredName, responsibilities, schools, and skills.
• To update the following properties, you must specify them in their own PATCH request, without including the other properties listed in the table above: aboutMe, birthday, interests, mySite, pastProjects, preferredName, 
responsibilities, schools, and skills.

Which means that using an app only permissions we cannot update birthday and hiredate. What is the alternative here? Use delegated permissions? Is this possible in Azure Functions using Graph .NET SDK? If yes, how?
I am using the following code to get to update the hiredate and birthday:

Code:

GraphServiceClient graphServiceClient = GetAuthenticatedGraphClient();
                    IGraphServiceUsersCollectionPage filteredUsers = await graphServiceClient.Users
                        .Request()
                        .Filter(string.Format("userPrincipalName eq '{0}'", employee.Email))
                        .Select("Id")
                        .GetAsync();

                    User? currentUser = filteredUsers.FirstOrDefault();

                    if (currentUser != null)
                    {
                        User userUpdate = new User()
                        {
                            Birthday = employee.BirthDate,
                            HireDate = employee.HireDate
                        };

                        await graphServiceClient.Users[currentUser.Id].Request().UpdateAsync(userUpdate);
                    }
private static GraphServiceClient GetAuthenticatedGraphClient()
{
// https://briantjackett.com/2019/12/12/creating-a-c-azure-function-to-call-microsoft-graph/
var authenticationProvider = CreateAuthorizationProvider();
GraphServiceClient graphServiceClient = new GraphServiceClient(authenticationProvider);
return graphServiceClient;
}
    private static IAuthenticationProvider CreateAuthorizationProvider()
    {
        // https://briantjackett.com/2019/12/12/creating-a-c-azure-function-to-call-microsoft-graph/
        var clientId = AppSettings.AzureADClientId;
        var clientSecret = AppSettings.AzureADClientSecret;
        var redirectUri = AppSettings.RedirectURL;
        var tenantId = AppSettings.TenantID;
        var authority = $"https://login.microsoftonline.com/{tenantId}/v2.0";

        //this specific scope means that application will default to what is defined in the application registration rather than using dynamic scopes
        List<string> scopes = new List<string>();
        scopes.Add("https://graph.microsoft.com/.default");

        var cca = ConfidentialClientApplicationBuilder.Create(clientId)
                                          .WithAuthority(authority)
                                          .WithRedirectUri(redirectUri)
                                          .WithClientSecret(clientSecret)
                                          .Build();

        return new MsalAuthenticationProvider(cca, scopes.ToArray());
    }

But getting the following error:

Microsoft.Graph.ServiceException
  HResult=0x80131500
  Message=Code: -1, Microsoft.Office.Server.Directory.DirectoryObjectUnauthorizedAccessException
Message: Attempted to perform an unauthorized operation.
Inner error:
	AdditionalData:
	date: 2022-04-16T14:35:23
	request-id: 94873bb0-3763-4e2b-88b6-6bc00f56c905
	client-request-id: 94873bb0-3763-4e2b-88b6-6bc00f56c905
ClientRequestId: 94873bb0-3763-4e2b-88b6-6bc00f56c905

  Source=Microsoft.Graph.Core
  StackTrace:
   at Microsoft.Graph.HttpProvider.<SendAsync>d__18.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Graph.BaseRequest.<SendRequestAsync>d__40.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Graph.BaseRequest.<SendAsync>d__34`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Graph.UserRequest.<UpdateAsync>d__7.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

The permissions I have in Azure AD are:

![image](https://user-images.githubusercontent.com/5429152/163679283-2557e3ec-2c66-4427-b248-d2339e55e19d.png)

Can you help? 

Thanks

**Comment by MIchaelMainer** [comment] 2022-04-19 18:07
I'm sorry to share that this is a duplicate of https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/296. I've created the following feature request, please up vote it.

https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/enable-update-hiredate-and-birthday-for-application-perm/idi-p/3289514

I'm sorry to say that there isn't a change that we can make in the client library to enable this feature.

**Closed by MIchaelMainer** 2022-04-19 18:07 UTC
Labels: Needs: Triage

**Comment by miguelisidoro** [comment] 2022-04-19 23:05
Hello @MIchaelMainer , I understand may be a duplicate in some way and I have already upvoted, thanks for creating the feature request in Tech Community.
However, my question is: is there any workaround while app only permissions do not allow to update hiredate and birthday? What is the alternative here? Use delegated permissions? Is this possible in Azure Functions using Graph .NET SDK? If yes, how?

Thanks

**Comment by MIchaelMainer** [comment] 2022-04-19 23:24
@miguelisidoro There isn't a supported way to go about this. To use the delegated permission, you'd need to have the user interact with an application, grab the token and refresh token, pass those to your Azure Function app, and then refresh the token from the Azure Function. I have no idea if this is supported.  I have no idea if this would work long term.

**Comment by miguelisidoro** [comment] 2022-04-19 23:33
Hello @MIchaelMainer thanks. I have to say I am disappointed at Microsoft and the Graph team. This is a pretty common scenario and I can't figure out why this topic that was discussed in 2018 was not solved by MS.

Updating these properties shouldn't be that hard using Graph.

Any other way to update these Azure AD properties besides using Graph? Is there any other API that we can use to update hiredate and birthday?

Thanks

**Comment by miguelisidoro** [comment] 2022-04-21 21:54
Hello, 

I managed to solve the problem. Adding Sites.FullControl.All in my App Registration since this properties are in SharePoint user profiles.

Thanks
Miguel

**Comment by MIchaelMainer** [comment] 2022-04-21 22:58
> Hello @MIchaelMainer Michael Mainer FTE thanks. I have to say I am disappointed at Microsoft and the Graph team. This is a pretty common scenario and I can't figure out why this topic that was discussed in 2018 was not solved by MS.

I think your feelings are justified. 

> I managed to solve the problem. Adding Sites.FullControl.All in my App Registration since this properties are in SharePoint user profiles.

I'm blown away that this works. Kudos to you for finding this, I'm sorry that you had to spend what I assume was trial and error to find that.

@zengin check out this permission scenario.

**Comment by zengin** [comment] 2022-04-21 23:13
cc: @Jackson-Woods @pixieofhugs
