### ISSUE TITLE
[Client bug]: Updating Microsoft.Graph to version 4.12.0 (or later) breaks the GraphServiceClient's constructor call

### ISSUE THREAD

**Issue by licdar87** [microsoftgraph/msgraph-sdk-dotnet#1380] opened 2022-06-09 10:49 UTC
As the subject says, updating the package via NuGet makes the build fail with the following errors:

> Error CS1503: Argument 1: cannot convert from 'Azure.Identity.ClientSecretCredential' to 'Microsoft.Graph.IAuthenticationProvider'
> Error CS1503: Argument 2: cannot convert from 'string[]' to 'Microsoft.Graph.IHttpProvider'	

The line of code where the issue occurs is:

> using Azure.Identity;
> using Microsoft.Graph;

> var graphClient = new GraphServiceClient(_clientSecretCredential, _scopes);

(documentation link: https://docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?tabs=CS#using-a-client-secret)

**To Reproduce**
All I need to do is update the package via NuGet to any subsequent version of 4.11.0

**Expected behavior**
No errors, build successful

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit
 - Version 22

Thank you

**Comment by licdar87** [comment] 2022-06-09 10:52
Just to be clear: switching back to version 4.11.0 and earlier fixes the problem

**Comment by licdar87** [comment] 2022-06-13 10:27
> Any chance you could provide more information on the dotnet runtime you are using and possibly other packages in your solution?

Right, I forgot to mention this: 

Dotnet runtime is 4.6.1 

These are all the packages currently listed on my web.config:

> name="System.Numerics.Vectors"
> version="4.1.4.0"
> 			
> name="System.Buffers" 
> version="4.0.3.0"
> 			
> name="System.Runtime.InteropServices.RuntimeInformation" 
> version="4.0.2.0"
>       
> name="WebGrease" publicKeyToken="31bf3856ad364e35"
> version="1.5.2.14234"
>       
> name="Newtonsoft.Json" 
> version="10.0.0.0"
>       
> name="Antlr3.Runtime" 
> version="3.5.0.2"
>       
> name="System.Web.Helpers" 
> version="3.0.0.0"
>       
> name="System.Web.WebPages" 
> version="3.0.0.0"
>       
> name="System.Web.Mvc" 
> version="5.2.7.0"
>       
> name="Azure.Core" 
> version="1.19.0.0"
>       
> name="System.ValueTuple" 
> version="4.0.3.0"
>       
> name="System.Threading.Tasks.Extensions" 
> version="4.2.0.1"
>       
> name="Microsoft.Identity.Client" 
> version="4.36.1.0"
>       
> name="System.Diagnostics.DiagnosticSource" 
> version="5.0.0.1"
>       
> name="System.Text.Json" 
> version="5.0.0.2"
>       
> name="System.Text.Encodings.Web" 
> version="5.0.0.1"
>       
> name="System.Runtime.CompilerServices.Unsafe" 
> version="5.0.0.0"
>       
> name="Microsoft.Bcl.AsyncInterfaces" 
> version="5.0.0.0"
>       
> name="System.Net.Http" 
> version="4.2.0.0"
>       
> name="Microsoft.Graph.Core" 
> version="2.0.8.0"

Thanks in advance

**Comment by zengin** [comment] 2022-06-18 00:32
This looks like an ambiguous type resolution to me where the type system is trying to interpret the input for another constructor than the intended one based on type hints available.

@licdar87, do you mind sharing the lines of code that initializes `_clientSecretCredential` and `_scopes` variables (with secrets hidden :))?

And if you are using Visual Studio for development, do you mind sharing which overloads of `GraphServiceClient` you get in Intellisense when you type `new GraphServiceClient()`?

Do you get all these 4 overloads? Is the experience the same when you can and can't repro the issue (i.e. 4.11.0 vs 4.12.0)?

![image](https://user-images.githubusercontent.com/803311/174414916-e05f3b65-2b6c-45a1-881c-4598b695745a.png)

![image](https://user-images.githubusercontent.com/803311/174415054-8437f7b7-1490-448d-b5ba-a5947e9ad72e.png)

![image](https://user-images.githubusercontent.com/803311/174415080-df4643f3-92c0-408a-9f0f-40da255c9ab5.png)

![image](https://user-images.githubusercontent.com/803311/174415037-dd6001b1-226b-4a4a-be30-0b572b9ca38b.png)

**Comment by licdar87** [comment] 2022-06-20 07:52
@zengin Thanks for the reply. Here's my code:

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Configuration;
using Azure.Identity;
using Microsoft.Graph;

static TestClass()
        {
            try
            {              
                _scopes = new[] { WebConfigurationManager.AppSettings["AZURE_APP_SCOPES"] };   
                _tenantId = WebConfigurationManager.AppSettings["AZURE_TENANT_ID"];        
                _clientId = WebConfigurationManager.AppSettings["AZURE_APP_ID"];
                _clientSecret = WebConfigurationManager.AppSettings["AZURE_APP_SECRET"];
                _options = new TokenCredentialOptions
                {
                    AuthorityHost = AzureAuthorityHosts.AzurePublicCloud
                };

                // https://docs.microsoft.com/dotnet/api/azure.identity.clientsecretcredential
                _clientSecretCredential = new ClientSecretCredential(
                _tenantId, _clientId, _clientSecret, _options);
            }
            catch (Exception e)
            {
                System.Diagnostics.Debug.Write(e.Message);
            }
        }
```

Regarding the overloading hints, Visual Studio (I'm on 2022) shows the exact same results as yours, in all cases (tried with 4.11.0, 4.12.0, and the latest stable 4.31.0)

**Comment by zengin** [comment] 2022-06-20 22:33
Ok, I was able to reproduce this, but only by moving the type hints in the object hierarchy, that is, when I declared the type of
- `_scopes` to be `object[]` instead of `string[]`
- or `_clientSecretCredential` to be `object` instead of `ClientSecretCredential`.

Declaration part is not visible with the code shared above, so it might be worth checking where `_scopes` and `_clientSecretCredential` are declared.

@licdar87, could you please check if `_scopes` is strictly declared as `string[]` and `_clientSecretCredential` as `ClientSecretCredential`?

When the type hints are not specific enough, the compiler matches with the first constructor with default parameters and complains that there is a type mismatch. It is still a mystery why the behavior would be different between 4.11 and 4.12 as the constructors stay the same between the versions, I wonder if there is a non-deterministic ordering of constructors in the assemblies between the two versions, which makes the compiler picking the right one in one of the versions. Regardless, I believe type hints specific enough should solve this issue IMO.

**Comment by licdar87** [comment] 2022-06-21 08:07
Now that I noticed it, the compiler errors are different from those I posted in the OP. I have absolutely no idea why that changed...

**Comment by zengin** [comment] 2022-06-22 21:45
@licdar87, thanks for additional information. I couldn't reproduce this with `static readonly` fields similar to above in an ASP.NET project targeting 4.6.1.

I know it might be a lot to ask but is there any chance you can isolate this behavior in a sample project in GitHub where we can play around with.

**Comment by zengin** [comment] 2022-06-23 18:35
@licdar87 it is expected to get this error when `Microsoft.Graph` is on v3.35 because that didn't have the constructor with TokenCredential. The isolated project doesn't reproduce the problem with 4.12 or higher either.

I will close this issue as updating the target framework seems to solve the issue. I am interested in knowing the root cause and please let us know if you figure it out, but I am glad to hear that there is an alternative solution to unblock you.

Thanks for using the Microsoft Graph SDK and reporting issues.

**Closed by zengin** 2022-06-23 18:35 UTC
Labels: Needs: Attention :wave:
