### ISSUE TITLE
Microsoft.Graph 5.0.0 incompatible with Azure Functions v4 [Microsoft.NET.Sdk.Functions 4.1.1]

### ISSUE THREAD

**Issue by lgiuliani80** [microsoftgraph/msgraph-sdk-dotnet#1670] opened 2023-03-02 10:38 UTC
**Describe the bug**
Graph APIs do not work, at least using client credentials, when in an .NET 6 Azure Function v4 (non isolated).
This exception is generation at GraphServiceClient construction:
```
Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Impossibile trovare il file specificato.
   at Microsoft.Kiota.Authentication.Azure.AzureIdentityAccessTokenProvider..ctor(TokenCredential credential, String[] allowedHosts, ObservabilityOptions observabilityOptions, String[] scopes) in /_/src/AzureIdentityAccessTokenProvider.cs:line 46
   at Microsoft.Graph.Authentication.AzureIdentityAccessTokenProvider..ctor(TokenCredential credential, String[] allowedHosts, ObservabilityOptions observabilityOptions, String[] scopes) in /_/src/Microsoft.Graph.Core/Authentication/AzureIdentityAccessTokenProvider.cs:line 18
   at Microsoft.Graph.GraphServiceClient..ctor(TokenCredential tokenCredential, IEnumerable`1 scopes, String baseUrl) in /_/src/Microsoft.Graph/GraphServiceClient.cs:line 52
```
**To Reproduce**
This is a simple C# code to reproduce the issue:

```cs
public class Functions
{
    private readonly IConfiguration _config;

    public Functions(IConfiguration config)
    {
        _config = config;
    }

    [FunctionName("HttpFuncTest")]
    public async Task<IActionResult> HttpFuncTest(
        [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] HttpRequest req,
        ILogger log)
    {
        log.LogInformation("Function started.");

        TokenCredential authProvider;

        var clientId = _config["AZUREAD_CLIENT_ID"];
        var tenantId = _config["AZUREAD_TENANT_ID"];
        var certThumbprint = _config["AZUREAD_CERT_THUMBPRINT"];

        if (!string.IsNullOrWhiteSpace(certThumbprint))
        {
            var store = new X509Store();
            store.Open(OpenFlags.ReadOnly | OpenFlags.OpenExistingOnly);
            var cert = store.Certificates.Find(X509FindType.FindByThumbprint, certThumbprint, false).FirstOrDefault();
            authProvider = new ClientCertificateCredential(tenantId, clientId, cert);
        }
        else
        {
            authProvider = new ClientSecretCredential(tenantId, clientId, _config["AZUREAD_CLIENT_SECRET"]);
        }

        var grcli = new GraphServiceClient(authProvider); // the exception in generated HERE
        var devices = await grcli.Devices.GetAsync();

        return new OkObjectResult(devices.Value);
    }
}
```

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.8.2" />
    <PackageReference Include="Microsoft.Graph" Version="5.0.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.1.1" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>

```

**Expected behavior**
I expect it to work.

**Additional context**
**IMPORTANT!** The same code **works** as expected downgrading to Microsoft.Graph 4.0.0, so this bug was _introduced_ in between the two major versions 4 and 5.

**Comment by andrueastman** [comment] 2023-03-03 05:50
Thanks for raising this @lgiuliani80,

I believe this is related to https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1598 and is caused by the Runtime not having the latest dependencies available. 

Any chance you have tried to follow the guide here for running C# Azure Functions in an isolated worker process?

https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#why-net-functions-isolated-worker-process

**Comment by lgiuliani80** [comment] 2023-03-03 07:28
Yes, it is surely a child of the bug you mentioned.
I have not tested with an isolated function as I do not want to use them (for the moment).
I assume that the Graph API SDK, one of the most importante MS modern SDKs should work everywhere, including non-isolated Azure Functions, especially since the previous versions of the same SDK worked seemlessy.
In any case I will try to make a new example using an isolated function and report you back.

Regards,

Luca


Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by acolom** [comment] 2023-03-03 09:02
We are facing the same problems, it would be usefull if a workaround can be provided

**Comment by lgiuliani80** [comment] 2023-03-03 20:02
Just for you all to know, I tried with a .NET 6 ISOLATED Function v4 and it is working.

**Comment by jamesmcroft** [comment] 2023-03-04 15:02
As with others, looking for workarounds that don't rely on changing the fundamental architecture of my Azure Functions to accommodate this.

**Comment by luukgortzak** [comment] 2023-03-08 13:20
We found a workaround by adding the following itemgroup in our Function app csproj.

```
<ItemGroup>
    <FunctionsPreservedDependencies Include="System.Text.Json.dll" />
    <FunctionsPreservedDependencies Include="System.Diagnostics.DiagnosticSource.dll" />
    <FunctionsPreservedDependencies Include="System.Text.Encodings.Web.dll" />
</ItemGroup>
```
System.Text.Json and System.Diagnostics.DiagnosticSource where assemblies that could not be found while creating the GraphServiceClient.
System.Text.Encodings.Web was not found while using the large file upload method.

This seems to work for Microsoft.Graph version 4.54.0, atleast for us to upload large files using Microsoft Graph.
It also allows me to create the GraphServiceClient while using version 5.0.0 but I haven't tried actually using it to upload files yet since I need to get around the breaking changes first. Will update when I do know.

**Comment by andrueastman** [comment] 2023-03-10 08:49
Thanks for this @luukgortzak,

We'll also be updating the abstraction libraries to use sliding version of `System.Text.Json` and `System.Diagnostics.DiagnosticSource` to include v6 versions so as to close this issue via  https://github.com/microsoft/kiota-abstractions-dotnet/pull/73 and https://github.com/microsoft/kiota-http-dotnet/pull/89

**Closed** 2023-03-10 13:13 UTC
Labels: Bug, Question: SDK
