### ISSUE TITLE
[Client bug]: Graph SDK 4.0 serialization payload broken

### ISSUE THREAD

**Issue by jackry** [microsoftgraph/msgraph-sdk-dotnet#1109] opened 2021-08-18 20:30 UTC
**Describe the bug**
I'm trying to update Graph SDK from 3.x to 4.2.0 (latest) in our project. There are several breaking changes on 4.0, which caused the serialization logic changed. It broke our test cases (deserialization failures). And I also have concern that it will break the logic on other project which makes the upgrade. Basically, we expect to keep the format of the serialized string, so that there won't cause any compatibility issue or regressions.
We just updated Microsoft.Graph to 4.2.0 and Microsoft.Graph.Core to 2.0.2. And we didn't change anything else. But we start getting a lot of unit test failures because of such serialization format change.

**To Reproduce**
For example, with following test code:
```
var request = client.Communications.Calls.LogTeleconferenceDeviceQuality(new TeleconferenceDeviceQuality()
{
    DeviceName = "Agent",
    MediaQualityList = new List<TeleconferenceDeviceMediaQuality>()
    {
        new TeleconferenceDeviceScreenSharingQuality()
        {
            AverageInboundJitter = new Duration(TimeSpan.FromMilliseconds(20)),
        },
    },
}).Request();
```

**Expected behavior**
Graph SDK 3.x will serialize to
```
{
  "quality": {
    "@odata.type": "#microsoft.graph.teleconferenceDeviceQuality",
    "deviceName": "Agent",
    "mediaQualityList": [
      {
        "@odata.type": "#microsoft.graph.teleconferenceDeviceScreenSharingQuality",
        "averageInboundJitter": "PT0.02S"
      }
    ]
  }
}
```

But Graph SDK 4.x will serialize to (The averageInboundJitter is broken, The format to provide odata type is also changed)
```
{
  "quality": {
    "deviceName": "Agent",
    "mediaQualityList": [
      {
        "averageInboundJitter": {},
        "oDataType": "microsoft.graph.teleconferenceDeviceScreenSharingQuality"
      }
    ]
  }
}
```

**Screenshots**
N/A

**Client version**
Microsoft.Graph 4.2.0
Microsoft.Graph.Core 2.0.2

**Desktop (please complete the following information):**
N/A.

**Additional context**
 
[AB#10777](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10777)

**Comment by pschaeflein** [comment] 2021-08-19 00:01
There is quite a difference between Newtonsoft.Json and System.Text.Json. [Official guidance covers the differences](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to?pivots=dotnet-core-3-1).

I just converted the [Graph Community library](https://github.com/microsoftgraph/msgraph-sdk-dotnet-contrib/tree/graph-v4), and I needed to create some [custom converters](https://github.com/microsoftgraph/msgraph-sdk-dotnet-contrib/tree/graph-v4/src/Serializer). That may help, but I would not consider it a trivial task.

I would not consider what you are seeing as a bug tho. I don't think the serialized payloads are what most expect from the SDK. And, the objects returned by the SDK are subject to change every week as the service grows, so I'm not sure why the specific format of the serialized objects matters.

**Comment by andrueastman** [comment] 2021-08-19 06:50
@jackry Thanks for opening this issue. 

With 4.2.0 this is the payload I get on serialization, 

```json
{
    "quality": {
        "deviceName": "Agent",
        "mediaQualityList": [{
            "averageInboundJitter": "PT0.02S",
            "@odata.type": "microsoft.graph.teleconferenceDeviceScreenSharingQuality"
        }]
    }
}
```

I suspect that there might be a configuration issue with your project as you might be calling a different serializer like Newtonsoft to serialize the payload. 
This is because your serialization payload shows that it is not able to infer the right name for the `OdataType` property from the attribute [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/4dd7864ff32ae736b5cfc5419a1c6e478ef0c487/src/Microsoft.Graph/Generated/model/TeleconferenceDeviceQuality.cs#L103).

Are you able to share how you are sending the request itself or calling the serializer? The sample code you provided does not seem to build the request to the point of calling the in-built serializer as it only returns the request object.

**Comment by andrueastman** [comment] 2021-08-19 07:37
Closing this for now as it is confirmed that the issue is caused by using NewtonSoft with the v4 models.

**Closed by andrueastman** 2021-08-19 07:37 UTC
Labels: under investigation, Needs: Author Feedback
