### ISSUE TITLE
How to handle expected errors from Create/GET Team "POST /teams" API or any other API

### ISSUE THREAD

**Issue by sanket10** [microsoftgraph/msgraph-sdk-dotnet#1024] opened 2021-06-02 06:31 UTC
**Describe the bug**
How to handle an expected "Bad Request or Authentication" error from "GET /teams({teamId})" or any other API. Currently, it throws "Null reference" Exception.

**Screenshots**
![image](https://user-images.githubusercontent.com/11810029/120434407-13d46a80-c39a-11eb-9220-b7d7e9f1fabd.png)
 
**Expected behavior**
Must provide proper HTTPResponse(status code, error message) if API fails,

**Comment by andrueastman** [comment] 2021-06-02 06:59
@sanket10 
Thanks for raising this issue. Are you able to provide the version of the SDK you are using?

**Comment by sanket10** [comment] 2021-06-02 08:01
It's 3.33.0

**Comment by andrueastman** [comment] 2021-06-02 12:15
Thanks for the info. I initially thought this was an issue caused by an older version of the sdk.
Are you able to provide the stack trace of the NullReference exception and possibly a trace of the request/response(e.g. using Fiddler) to help figure out the issue?

**Comment by sanket10** [comment] 2021-06-02 12:34
Exception with wrong teamId -
![image](https://user-images.githubusercontent.com/11810029/120480450-ab52b100-c3cc-11eb-9ec6-356a6c66d16b.png)

Stacktrace - 
   at Microsoft.Graph.HttpProvider.<SendAsync>d__18.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Graph.BaseRequest.<SendRequestAsync>d__38.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Graph.BaseRequest.<SendAsync>d__34`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Graph.TeamRequest.<GetAsync>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at E2E_Test.Program.<AsyncUsingUserNameProviderToCreateTeam>d__11.MoveNext() in C:\Users\sanjai\source\repos\E2E_Test\E2E_Test\Program.cs:line 101

Error Message - Object reference not set to an instance of an object.

**Comment by andrueastman** [comment] 2021-06-03 09:08
Any chance you got a trace of the request/response(e.g. using Fiddler) to help figure out the issue?

**Comment by sanket10** [comment] 2021-06-04 06:20
Hey @andrueastman ,
I can't see any "GET /teams({'teamId'})" requeust in my fiddler traces. I hit GET API multiple time in an execution but only see one log - 
![image](https://user-images.githubusercontent.com/11810029/120754837-d05d3600-c52a-11eb-8d7b-4ac647c5baf2.png)

**Comment by andrueastman** [comment] 2021-06-04 06:24
I believe HTTPS traffic is disabled by default on Fiddler.

You can go to View >> Preferences >> HTTPS 

Then check the "Capture HTTPS traffic" checkbox.

**Comment by sanket10** [comment] 2021-06-04 06:49
Thanks @andrueastman ,
Now I can see my request - 
![Uploading image.png…]()

**Comment by andrueastman** [comment] 2021-06-04 06:56
> It's 3.33.0

It looks like from the sdk version header, you are using the 2.0.0 version of core which is not compatible with sdk version 3.33.0.

Are you able to confirm from the project csproj your package versions again?

**Comment by sanket10** [comment] 2021-06-04 07:10
Yes, it's 3.33.0

**Comment by andrueastman** [comment] 2021-06-04 07:18
For Microsoft.Graph 3.33.0 you want to use latest stable Microsoft.Graph.Core i.e. 1.25.1. Could you try it out and see if the issue replicates is resolved for you?

The 2.x.x versions have breaking changes and are compatible with the Microsoft.Graph 4.x.x versions. These are still in preview. You can check more info [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/935)

**Comment by sanket10** [comment] 2021-06-04 07:30
Yes, now it's working.
It throws "Mircosoft.Graph.ServiceException" in case of "Bad Request".
Thanks @andrueastman for this help.

**Comment by andrueastman** [comment] 2021-06-04 08:14
No worries about that. Closing this now as this is resolved.

**Closed by andrueastman** 2021-06-04 08:14 UTC
Labels: more-information-needed
