### ISSUE TITLE
Need c# example to insert an image into excel worksheet using Microsoft graph SDK

### ISSUE THREAD

**Issue by Akhil9802** [microsoftgraph/msgraph-sdk-dotnet#1424] opened 2022-07-22 19:02 UTC

**Comment by ddyett** [comment] 2023-03-09 02:48
@maisarissi to determine need.

**Comment by sebastienlevert** [comment] 2024-04-12 14:37
Thank you for reporting this issue. This appears to be an issue or limitation with the service APIs. Unfortunately, as the Microsoft Graph SDK team, we do not have ownership of the APIs that are causing you issues. We invite you to create a question about the service API to Microsoft Q&A and tagged with one of the [microsoft-graph-*](https://docs.microsoft.com/en-us/answers/search.html?c=&includeChildren=&f=&type=question+OR+idea+OR+kbentry+OR+answer+OR+topic+OR+user&redirect=search%2Fsearch&sort=relevance&q=microsoft-graph-*) tags, that way it will get routed to the appropriate team for them to triage.

For now, we will close the issue on our side but feel free to reopen if you think the issue is specific to this SDK.

Please let us know if this helps!

**Closed** 2024-08-14 07:23 UTC
Labels: Question: SDK, Status: No recent activity, status:waiting-for-author-feedback
