### ISSUE TITLE
Is there anyway way to get a callRecord by Id through the SDK?

### ISSUE THREAD

**Issue by julienFlexsoft** [microsoftgraph/msgraph-sdk-dotnet#752] opened 2020-07-30 13:03 UTC
**Is your feature request related to a problem? Please describe.**
I need to show the user of my app his/her call history. Since there is no endpoint to get a list I created a subscription to the "communications/callRecords" resource. When a call is made, my webhook gets triggered. All this works well, I get the Id of the new callRecord but now I want to go get more data from the callRecord. Is there a way to get it through the SDK? Or is it only available with a manual request to the API?

**Describe the solution you'd like**
I am looking for something like this:
```
CallRecord callRecord = await graphServiceClient.Communications.CallRecords[id]
 .Request()
 .GetAsync();
```

**Describe alternatives you've considered**
The only alternative I found is to make the call manually, which isn't an issue, just a far less clean solution.

**Comment by zengin** [comment] 2020-07-30 18:08
duplicate of https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/issues/248

**Closed** 2020-07-31 19:00 UTC
Labels: ToTriage, duplicate, request: feature
