### ISSUE TITLE
Error occured when making a request with the page iterator 

### ISSUE THREAD

**Issue by mewanZCW** [microsoftgraph/msgraph-sdk-dotnet#2291] opened 2024-01-17 02:19 UTC
Library version used
5.38.0

.NET version
.Net 8.0

I get this error in my console app when try to get all the file and folders count from a sharepoint list.
unauthenticated : Invalid audience Uri '00000003-0000-0000-c000-000000000000'
This was working fine before without any issues and there wasn't any code or library changes. Then I tried upgrading the libraries, But no change. I'm using "microsoft.com/devicelogin" to authenticate. I tried with a token that generated from the Graph explorer and got the same error. But Still I can upload document and get sharepoint lists in the site from my code. In reading sharepoint lists method also has the same code with the PageIterator and it works fine.

this is the GetShrepointLibraries  method  which is working fine

```
public async Task<List<List>> GetSharePointLibraries(string siteId)
{
    if (string.IsNullOrEmpty(siteId))
    {
        throw new ArgumentNullException(nameof(siteId));
    }

    List<List> allItems = new List<List>();

    var siteResponse = await _graphClient.Sites[siteId].Lists.GetAsync(requestConfig =>
    {
        requestConfig.QueryParameters.Expand = new string[] { "Drive" };
    });

    var pageIterator = PageIterator<List, ListCollectionResponse>
        .CreatePageIterator(_graphClient, siteResponse,
        (lib) =>
        {
            allItems.Add(lib);
            return true;
        });

    await pageIterator.IterateAsync();
    return allItems;
}
```

In "GetLibraryItemsCount" still I get the first 200 items in the first resqust and get the error in the next request.
Also tried with limited to 10 at a time and when it try for the next 10 items, I get the error.

Also I already included those scopes.

MsGraphScope = new string[] { "User.Read", "Sites.Read.All", "Sites.Manage.All", "Sites.ReadWrite.All" };

Relevant code snippets

```
public async Task<int> GetLibraryItemsCount(string driveId)
{
    List<DriveItem> items = new List<DriveItem>();
    var allItems = await _graphClient.Drives[driveId].Items.GetAsync((requestConfiguration) =>
    {
        requestConfiguration.QueryParameters.Filter = "folder ne null or file ne null";
    });

    var pageIterator = PageIterator<DriveItem, DriveItemCollectionResponse>
            .CreatePageIterator(_graphClient, allItems,
            (i) =>
            {
                items.Add(i);
                return true;
            });

    await pageIterator.IterateAsync();

    return items.Count;
}
```

**Expected behavior**
"GetLibraryItemsCount" should return all item count within the list.

**Desktop**
 - OS: Windows 10 Bussiness 64bit (10.0 Build 19045)
 - Browser : MS Edge
 - Browser Version 120.0.2210.133 (Official build) (64-bit)

**Comment by andrueastman** [comment] 2024-01-17 06:50
Thanks for raising this @mewanZCW 

Any chance you can print out the value of `allItems.OdataNextLink` and confirm if you can past the URL on graph explorer and make a successfull call if you past back to the graph explorer(as you are using the same token)? Is the url similar to other graph urls?

**Comment by mewanZCW** [comment] 2024-01-17 07:35
> Thanks for raising this @mewanZCW
> 
> Any chance you can print out the value of `allItems.OdataNextLink` and confirm if you can past the URL on graph explorer and make a successfull call if you past back to the graph explorer(as you are using the same token)? Is the url similar to other graph urls?


this is how the OdataNextLink looks like 

https://xxxxxxxx.sharepoint.com/_api/v2.0/drives('driveid/items?$filter=folder+ne+null+or+file+ne+null&$skiptoken=token

this is not looks like the graph url. if I replace https://xxxxxxxx.sharepoint.com/_api/v2.0 with https://graph.microsoft.com/v1.0 graph explorer give me the result. Not sure why this url is incorrect

**Comment by andrueastman** [comment] 2024-01-17 09:40
This is an API related issue. We're following this up with the team as the returned odata.nextLink url should be have the `graph.microsoft.com` host. 

https://portal.microsofticm.com/imp/v3/incidents/details/459792946/home

**Comment by mewanZCW** [comment] 2024-01-17 21:42
> This is an API related issue. We're following this up with the team as the returned odata.nextLink url should be have the `graph.microsoft.com` host.
> 
> https://portal.microsofticm.com/imp/v3/incidents/details/459792946/home

Thanks @andrueastman for helping me to identify the issue
For now I can manually do the iteration and  change the host and keep continue my work. But when can I get a possible fix for this.

**Comment by andrueastman** [comment] 2024-01-18 06:34
We'll need to get feedback from the API team on when the fix will be resolved. We will update here once we get confirmation from them.

**Comment by mewanZCW** [comment] 2024-01-24 21:40
@andrueastman Is there any update on this?

**Comment by mewanZCW** [comment] 2024-01-30 00:58
@andrueastman  At the moment, I implemented a workaround to make this work by obtaining the **OdataNextLink**, replacing the domain, and calling the next page by parsing a fixed URL with '**WithUrl**.' It's functional, but it's inefficient. Is there a better way to handle this until the issue is fixed?

**Comment by andrueastman** [comment] 2024-02-16 10:48
> This is an API related issue. We're following this up with the team as the returned odata.nextLink url should be have the `graph.microsoft.com` host.
> 
> https://portal.microsofticm.com/imp/v3/incidents/details/459792946/home

Feedback from the API team is that making requests to the specific path is not a supported path from the Graph API (and not documented) and https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2316#issuecomment-1928965371 suggests the same. 

https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2316#issuecomment-1935633315 suggests the issue is fixed but the recommendation here is that since the path is not technically supported by the API team, it should not really be used/called.

I would suggest creating a ticket here for the API owners to add support for this. (You can post this back here as a comment so that anyone who comes across this may upvote it as well). Closing this for now.

**Closed by andrueastman** 2024-02-16 10:48 UTC
Labels: Service issue

**Comment by fzbm** [comment] 2024-04-17 11:31
It looks like the issue resurfaced again at least a few days ago. Just executing a `GET /me/drive/following` request result in `nextLink` URLs containing a SharePoint host name. We added a workaround which modifies the URL of a `nextLink` to replace the wrong SharePoint URL with a Graph one.

**Comment by celluj34** [comment] 2024-05-21 21:08
This is our workaround for the time being:

```csharp
var driveItems = new List<DriveItem>();

var iterator = PageIterator<DriveItem, DriveItemCollectionResponse>.CreatePageIterator(_graphClient,
    modifiedItems,
    x =>
    {
        if (x is not null)
        {
            driveItems.Add(x);
        }

        return true;
    },
    x =>
    {
        if (x.URI.Host is "graph.microsoft.com")
        {
            return x;
        }

        var builder = new UriBuilder(x.URI)
        {
            Host = "graph.microsoft.com"
        };

        builder.Path = builder.Path.Replace("_api/v2.0", "v1.0");

        x.URI = builder.Uri;

        return x;
    });
```
