### ISSUE TITLE
URL built by the SDK doesn't match with the URL expected by the service

### ISSUE THREAD

**Issue by zengin** [microsoftgraph/msgraph-sdk-dotnet#1156] opened 2021-10-22 00:39 UTC
Original HTTP snippet from [the docs](https://docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-filterbycurrentuser?view=graph-rest-1.0&tabs=http#request)
```http
GET https://graph.microsoft.com/v1.0/identityGovernance/accessReviews/definitions/filterByCurrentUser(on='reviewer')
```

C# Snippet:
```csharp
GraphServiceClient graphClient = new GraphServiceClient( authProvider );

var filterByCurrentUser = await graphClient.IdentityGovernance.AccessReviews.Definitions
	.FilterByCurrentUser(AccessReviewScheduleDefinitionFilterByCurrentUserOptions.Reviewer)
	.Request()
	.GetAsync();
```

When executed, the URL becomes:
```http
https://graph.microsoft.com/v1.0/identityGovernance/accessReviews/definitions/microsoft.graph.filterByCurrentUser(on=Reviewer)
```

And the service returns the following error:
```json
{
    "error": {
        "code": "BadRequest",
        "message": "The parameter 'on=Reviewer' is not in scope.",
        "innerError": {
            "date": "2021-10-22T00:33:40",
            "request-id": "d6262272-9b0e-455e-a081-726be78e7b60",
            "client-request-id": "2f0a0d8a-626f-f9ec-f543-98f36c191681"
        }
    }
}
```

Following two changes don't make a difference:
- Fully qualified function name `microsoft.graph.filterByCurrentUser` vs `filterByCurrentUser`
- PascalCase vs camelCase i.e. `Reviewer` vs `reviewer`.

Service works fine if the quotes are present.

@andrueastman @MIchaelMainer, I haven't had a chance to dig into the OData spec for this. Do you know whether
1. the URL we generate should be allowed by the spec and service needs to be fixed or 
2. should we fix our URL builder in the SDK?

cc: @darrelmiller @baywet

**Comment by zengin** [comment] 2021-10-22 04:56
Here is another example where quoted function parameter value works but SDK doesn't put the quotes in the URL:
https://docs.microsoft.com/en-us/graph/api/outlookuser-supportedtimezones?view=graph-rest-1.0&amp%3Btabs=csharp&tabs=http#request-2

succeeds:
```
https://graph.microsoft.com/v1.0/me/outlook/microsoft.graph.supportedTimeZones(timeZoneStandard='Iana')
```

fails:
```
https://graph.microsoft.com/v1.0/me/outlook/microsoft.graph.supportedTimeZones(timeZoneStandard=Iana)
```

**Comment by baywet** [comment] 2021-11-17 19:37
reviewing from the kiota checklist.

I'm not sure which one is faulty here: the conversion process doesn't add the quotes either for the filterByCurrentUser method, which results in [not having them in the url template](https://github.com/microsoftgraph/msgraph-sdk-go/blob/63d146b9a9e6c9f8dce806eb2a5cafdc4e0e392a/identitygovernance/accessreviews/definitions/filterbycurrentuserwithon/filter_by_current_user_with_on_request_builder.go#L34)

However, when the parameter is a string, it does add them (e.g. allowedCalendarSharingRoles). I believe the issue is actually on the service side here, because the on parameter is a complex type, the service should NOT expect quotes, but it seems to be expecting them.

**Comment by zengin** [comment] 2021-11-18 23:17
@baywet, `on` parameter is an enum type, not a complex type.

```xml
<Function Name="filterByCurrentUser" IsBound="true">
  <Parameter Name="bindingParameter" Type="Collection(graph.accessReviewScheduleDefinition)"/>
  <Parameter Name="on" Type="graph.accessReviewScheduleDefinitionFilterByCurrentUserOptions" Nullable="false"/>
  <ReturnType Type="Collection(graph.accessReviewScheduleDefinition)"/>
</Function>
```

```xml
<EnumType Name="accessReviewScheduleDefinitionFilterByCurrentUserOptions">
  <Member Name="reviewer" Value="1"/>
  <Member Name="unknownFutureValue" Value="2"/>
</EnumType>
```

And according to the spec, it seems that we need quotes around the type name but not the namespace:
http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#sec_PrimitiveLiterals
> `ColorEnumValue eq Sales.Pattern'Yellow',`
> `ColorEnumValue eq 'Yellow',`

Similarly `timeZoneStandard` is also an EnumType.

@andrueastman mentioned a piece of code from the Core library to put the quotes around, but @baywet pointed to a full URL template within kiota generated code. I know that the latter was Go, but I am wondering where this issue should be fixed once kiota becomes the generator for C#?

**Comment by baywet** [comment] 2021-11-19 13:44
Effectively the C# SDK will have a very similar "shape" to the Go SDK once it switches to Kiota (url templates and all).
Assuming the template is correct (no defect in the conversion process), and the service is doing what it's supposed to do (implementation matches odata spec) it should work.
As it stands now, it looks like the template is missing the quotes, and the service is doing the right thing. So it's probably an issue with the conversion process.
If you agree, let's crate an issue in the odata/openapi repo.

**Comment by zengin** [comment] 2021-11-19 20:18
agreed, opened an issue here: https://github.com/microsoft/OpenAPI.NET.OData/issues/140

**Comment by andrueastman** [comment] 2022-05-23 12:26
Closing this one for now. 
https://github.com/microsoft/OpenAPI.NET.OData/issues/140 has been resolved and the correct url template with single quotes is propagated to the SDK.

Ref shown below. 

https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/de957836a5ebea22878831da7488bb4a4f870f9e/src/Microsoft.Graph/Generated/IdentityGovernance/AccessReviews/Definitions/FilterByCurrentUserWithOn/FilterByCurrentUserWithOnRequestBuilder.cs#L27

**Closed by andrueastman** 2022-05-23 12:26 UTC
Labels: Status: Under investigation, Kiota
