### ISSUE TITLE
[Client bug]: Latest client in Azure Function runtime error looking for System.Diagnostics.DiagnosticSource 7.0.0

### ISSUE THREAD

**Issue by joshbinney** [microsoftgraph/msgraph-sdk-dotnet#1713] opened 2023-03-13 00:53 UTC
Getting a runtime error:
System.Private.CoreLib: Exception while executing function: MyFunction. Microsoft.Kiota.Authentication.Azure: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

This is running in the latest Azure Functions SDK 4.1.3

Seems some dependency somewhere wants 7.0.0 and something else is using the latest, 7.0.1. 

Client version 5.1.0

Running locally - Windows 10

**Comment by andrueastman** [comment] 2023-03-13 06:42
Thanks for raising this @joshbinney 

We'll close this as a duplicate of https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1670

Workaround provided at https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1670#issuecomment-1460147322

Kiota dependencies have been refactored to use range dependencies and should be fixed in the upcoming 5.2.0 release later in the week.

**Closed by andrueastman** 2023-03-13 06:42 UTC
Labels: Needs: Triage
