### ISSUE TITLE
Change Notifications - GraphServiceClient.HttpProvider replacement in .Net 7 / Microsoft.Graph 5.13

### ISSUE THREAD

**Issue by aldrashan** [microsoftgraph/msgraph-sdk-dotnet#1974] opened 2023-06-20 09:34 UTC
Please provide the following (and please check them off the list with [x]) before submitting this issue:
- [x] Expected behavior. Please provide **links to the specific [Microsoft Graph documentation](https://developer.microsoft.com/en-us/graph/docs/concepts/overview)** you used to determine the expected behavior. 
- [x] Actual behavior. Provide error codes, stack information, and a [Fiddler](http://www.telerik.com/fiddler) capture of the request and response (please remove personally identifiable information before posting).
- [x] Steps to reproduce the behavior. Include your code, IDE versions, client library versions, and any other information that might be helpful to understand your scenario.

### Expected behavior
We're currently setting up Change Notifications for the first time and followed the [documentation](https://learn.microsoft.com/en-us/graph/webhooks-with-resource-data). This all works up until the deserialization of the Change Notification Content.
[This "old" tutorial](https://github.com/microsoftgraph/aspnetcore-webhooks-sample/blob/main/src/GraphWebhooks/Controllers/ListenController.cs) uses _graphClient.HttpProvider.Serializer to deserialize the response, but this property doesn't exist anymore. 

We tried deserializing with System.Text.Json `System.Text.Json.JsonSerializer.Deserialize<Microsoft.Graph.Models.ChangeNotificationCollectionResponse>(content)` but then no properties contain values. 

<img width="779" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/20169019/d44a9b28-6d56-4051-ba58-62c2618c56d8">

We tried deserializing with Newtonsoft.Json `Newtonsoft.Json.JsonConvert.DeserializeObject<Microsoft.Graph.Models.ChangeNotificationCollectionResponse>(content)` but then the ResponseData property doesn't contain any values.

<img width="780" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/20169019/67630dcf-36e1-4e3c-904e-c79552eaa9d9">

### Actual behavior
Deserialization is incorrect.

We are using a beta endpoint (`users/x/messages?$select=id,conversationId`), but this shouldn't have any influence over the deserialization part, should it? Deserializing into a Microsoft.Graph.Beta.Models.ChangeNotificationCollectionResponse doesn't work either for both libraries.

### Steps to reproduce the behavior
This is the content string:
`{
  "value": [
    {
      "subscriptionId": "0f5fe882-db07-4222-9d68-67252364b79b",
      "subscriptionExpirationDateTime": "2023-06-20T09:26:11.6089067+00:00",
      "changeType": "created",
      "resource": "Users('redacted')/messages('redacted')",
      "clientState": "redacted",
      "tenantId": "redacted",
      "encryptedContent": {
        "data": "mN42tt+QnbbD83CXAYofok9+b/j1ozDojfiQ+Juzlt99u3tYMwmhu6b4XmUeyseGyxcmINBq6hHC1RXGJIa/qR1H7v/X7HYtd0wqdHB9MtF+x7TtwHfdvV/90AllsM7Bgwy3beFpkv6MXjmxB65DIw==",
        "dataKey": "a455ZC7r6MmkN0G5yM2a3X/+dMZhm4Z4KvxVZU8pXH/dcpIJzCAuw9rcMMKw3nTCMFpdQBq+DdSDcSXqAXXWza3pyAFzxL8uybTLvMIkpDAsdh1bddie356IEilzII360EDhlC4pgXR4CScjeCuredraz9EzS3nArpbzup+qZsFrUuSlosVRomftL5qjYZAB7DrcPKDVIP4rwT1oWoYudmKgvOuAYzc2nRnLsrnBc1/yW5wiTyXL4v/5MEJWq5B+XHxqBo/kwVqlyzTUqrrzVk6ruVO1hL7BIcSg412Ip4sPbt/Nc1AOvmcB+Ez/78//1ubPafj9/T7NLYpKvQbuNQ==",
        "dataSignature": "hpTO/e/oR/h8mSVbdWjLLjFTHyrIbKj0ehXwhTTyMqc=",
        "encryptionCertificateId": "redacted",
        "encryptionCertificateThumbprint": "9C98621988320AC9930FF62B9AB73A12B26BE18D"
      },
      "resourceData": {
        "@odata.type": "#microsoft.graph.message",
        "@odata.id": "Users('redacted')/messages('redacted')",
        "@odata.etag": "W/\"CQAAABYAAADev9p0GOhIRp89M6w55+QbAATsO+pQ\"",
        "id": "redacted"
      }
    }
  ],
  "validationTokens": [
    "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyIsImtpZCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyJ9.eyJhdWQiOiJmODhmM2Y2Yi1kZTNlLTQyNzYtODNkZS1jZjg5ZGE5MmVmZDkiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC85YTc2NGE4ZC0yNzVlLTQ4NzMtOWVmOS1kYjlhN2M5NWNlZmEvIiwiaWF0IjoxNjg3MjQxNjI1LCJuYmYiOjE2ODcyNDE2MjUsImV4cCI6MTY4NzMyODMyNSwiYWlvIjoiRTJaZ1lNaWJzVzBuMjl6Rmt0MzFKNU5TWkkxUEF3QT0iLCJhcHBpZCI6IjBiZjMwZjNiLTRhNTItNDhkZi05YTgyLTIzNDkxMGM0YTA4NiIsImFwcGlkYWNyIjoiMiIsImlkcCI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0LzlhNzY0YThkLTI3NWUtNDg3My05ZWY5LWRiOWE3Yzk1Y2VmYS8iLCJvaWQiOiI5M2RiODNhZi03NjVlLTQwMTMtODQwZi0yNzEyYTgyMTFlNzgiLCJyaCI6IjAuQVJFQWpVcDJtbDRuYzBpZS1kdWFmSlhPLW1zX2pfZy0zblpDZzk3UGlkcVM3OWtSQUFBLiIsInN1YiI6IjkzZGI4M2FmLTc2NWUtNDAxMy04NDBmLTI3MTJhODIxMWU3OCIsInRpZCI6IjlhNzY0YThkLTI3NWUtNDg3My05ZWY5LWRiOWE3Yzk1Y2VmYSIsInV0aSI6ImM0VGVWUTB1dlVDbmVPUlFDdGdvQUEiLCJ2ZXIiOiIxLjAifQ.DwMpgg-duzEUzLwOv8EZTWbHt-gPIBlLeokxIYvrHQZjyCQd5i7P8skW0ZgEfX8q4oGIwI7KXoZH1-UTiYZBjkBnhtsglrT1e45CIuTdPODaBrpJyiquDA2aQxLXTv_hqOY8jnTSKcuBggJbQDMsEqkodFPkPLZOZxO1affgLg4xRBfl47PHYBRwy6QwGCqGQASieRSGDwVdptfQaLhail3_w6dWNdwCcdkdpiTuWhSiwRfwJ3BnsazMKlyk0Qy-U2NSMX52cVI4rGjs5O7bL0G1oVn0fVhrTzDglXNd0RMieBwnMVRIwbIq1tfqSVjOhcTDBKvfqEbEufktnWxLyw"
  ]
}
`

Using

- Microsoft.Graph 5.13.0
- Microsoft.Graph.Beta 5.34.0-preview
- Newtonsoft.Json 13.0.3

**Comment by aldrashan** [comment] 2023-06-20 12:27
Stumbled upon a response within the [following issue](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1758#issuecomment-1548353976).

```
using var memoryStream = new MemoryStream(System.Text.Encoding.UTF8.GetBytes(content));
var parseNode = new JsonParseNodeFactory().GetRootParseNode(CoreConstants.MimeTypeNames.Application.Json, memoryStream);
var notifications = parseNode.GetObjectValue(Microsoft.Graph.Models.ChangeNotificationCollectionResponse.CreateFromDiscriminatorValue);
```

If you do it like this, then it appears to deserialize properly, but there's still no class you can deserialize that also contains the ValidationTokens property, so you still have to deserialize that manually.

**Comment by andrueastman** [comment] 2023-12-14 10:00
Closing this for now as a duplicate of https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2237. Issue will be tracked there

**Closed by andrueastman** 2023-12-14 10:00 UTC
