### ISSUE TITLE
Parsing members@delta in a group delta query

### ISSUE THREAD

**Issue by ssteiner** [microsoftgraph/msgraph-sdk-dotnet#501] opened 2019-06-24 18:27 UTC
I guess that's more of a feature request issue. I'm doing delta queries on groups with Expand() on members. So the raw json returned may contain a group having a members@delta tag containing an array of microsoft.graph.users identified by their id.

Looking at the object model, the content of members@delta go into the AdditionalData dictionary. So, it is then up to me to parse this and detect deletions vs. new adds.

Any chance to see helper properties for this? E.g. on the Group object a new property AddedMembers containing a User (with just the Id), and RemovedMembers also containing a list of Users (with just the Id).

**Comment by peombwa** [comment] 2019-06-27 22:51
@ssteiner This is a valid requests, and we tracking are already tracking deserialization of AdditionalData values in https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/384. I'll mark this as a duplicate of https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/384, but we will consider this scenario and suggestions when designing our implementation.

**Closed** 2019-06-28 23:00 UTC
Labels: duplicate
