### ISSUE TITLE
SetPresence broken for SDK > 4.7.0?

### ISSUE THREAD

**Issue by rekefjard** [microsoftgraph/msgraph-sdk-dotnet#1213] opened 2022-01-04 17:00 UTC
**Describe the bug**
Working app upgraded the SDK from 4.5.0 to 4.13.0 and SetPresence cannot change presence status. Downgrade to <= 4.7.0 resolves the issue.

**To Reproduce**
1. Upgrade SDK to 4.13.0
2. Use SDK call:
           client.Users[userId].Presence
                .SetPresence(clientId, availability, activity, expirationDuration)
                .Request()
                .PostAsync();
3. Verify the current presence status

**Expected behavior**
If the current presence status is Available/Available I should be able to change it to Busy/InACall.

**Screenshots**
N/A

**Client version**
4.8.0 to 4.13.0

**Desktop (please complete the following information):**
 - Windows 10/Server 2019
 - Browser N/A
 - Version N/A

**Additional context**
N/A

Regards Richard

**Comment by zengin** [comment] 2022-01-05 00:13
Looks like this is caused by parameter being marked as nullable:
https://github.com/microsoftgraph/msgraph-metadata/commit/48d226fe16f07d40575d778440d35ede6cea90ff#diff-3964e1d46914c457caec43f8f7aa1430a486f0a78419e24ec21e7f4e08cdf00eL26357

![image](https://user-images.githubusercontent.com/803311/148140036-3fe3a4e8-3787-49fc-80b3-69a5b565e65d.png)

Nullable parameters appear at the end of methods created from actions. So, marking the parameter nullable changed the parameter order.

cc: @andrueastman @baywet, this is another case where parameter objects will solve the issue in kiota generated SDKs.

Because we released 5 minor versions on top of this breaking change, reverting will also cause another breaking change. I will update this issue if we apply any fix regarding this.

@rekefjard, to unblock you, I would recommend using the new parameter order as defined here:

https://github.com/microsoftgraph/msgraph-sdk-dotnet/blame/dev/src/Microsoft.Graph/Generated/requests/PresenceRequestBuilder.cs#L70

e.g.
```csharp
client.Users[userId].Presence
  .SetPresence(availability, activity, clientId, expirationDuration)
  .Request()
  .PostAsync();
```

**Closed** 2022-01-12 02:00 UTC
Labels: Needs: Author Feedback, no-recent-activity
