### ISSUE TITLE
Unable to paginate through app role assignments for a service principal when both "filter" and "top" are specified

### ISSUE THREAD

**Issue by gmantri** [microsoftgraph/msgraph-sdk-dotnet#1054] opened 2021-07-04 07:31 UTC
**Describe the bug**
I am trying to get a list of app roles assignments for a service principal. 

When I specify both `filter` and `top` criteria, I am only getting the number of records specified through top criteria that matches the filter criteria however I don't get `next page link` as there are more records matching that filter criteria. 

If I specify either `filter` or `top`, everything works well.

Please see sample code below:

```
string servicePrincipalId = "7ec2f5c8-0689-41b1-ab2f-27fead345d78";
string filterCriteria = "Smith";
int? maxResults = 5;
IServicePrincipalAppRoleAssignedToCollectionRequest request = graphServiceClient.ServicePrincipals[servicePrincipalId].AppRoleAssignedTo.Request();

if (!string.IsNullOrWhiteSpace(filterCriteria))
{
    request = request.Filter($"startsWith(principalDisplayName, '{filterCriteria}')");
}
if (maxResults is > 0)
{
    request = request.Top(maxResults.Value);
}

IServicePrincipalAppRoleAssignedToCollectionPage result = await request.GetAsync();
var nextPageRequest = result.NextPageRequest;//This comes as null if both filterCriteria & maxResults are defined.
```

Because of this, I am not able to paginate.

Is this a bug in the SDK or does this operation not support pagination under this particular scenario?

**Additional context**
I am using `Microsoft.Graph (version 4.0.0-preview.6)` Nuget package.
 
[AB#10126](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10126)

**Comment by andrueastman** [comment] 2021-07-05 07:05
Hey @gmantri,
Thanks for raising this issue. 
Are you able to confirm by making the same request on Graph Explorer and confirm if there is an "odata.nextLink" property on the response payload? 
If not, the specific endpoint may not support paging when filter criteria is defined(or there may not be second page for the specific request you are making).

**Comment by gmantri** [comment] 2021-07-05 13:23
Hi @andrueastman - Thanks for replying. 

So when I execute the following request URI in Graph Explorer `https://graph.microsoft.com:443/v1.0/servicePrincipals/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/appRoleAssignedTo?`, I get 100 results back with `nextLink` property. This is correct as I have more than 100 app role assignments in my Azure AD for the Service Principal.

When I execute the following request URI in Graph Explorer `https://graph.microsoft.com:443/v1.0/servicePrincipals/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/appRoleAssignedTo?$filter=startsWith(principalDisplayName, 'G')`, I get 31 results back and no `nextLink` property. This is correct as I only have 31 users in my Azure AD whose display name starts with `G`.

When I execute the following request URI in Graph Explorer `https://graph.microsoft.com:443/v1.0/servicePrincipals/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/appRoleAssignedTo?$top=5`, I get 5 results back and at this time `nextLink` property is available in the response. This is also correct. I can use the `nextLink` property to get the next set of results.

Now, when I execute the following request URI in Graph Explorer `https://graph.microsoft.com:443/v1.0/servicePrincipals/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/appRoleAssignedTo?$filter=startsWith(principalDisplayName, 'G')&$top=5`, I only get 5 results back (which is correct) but no `nextLink` property. Considering there are 26 more users available, shouldn't the API be returning a `nextLink`?

I guess my question is that why is there an ambiguous behavior with  `$filter` and `nextLink`?

**Comment by andrueastman** [comment] 2021-07-05 16:02
Hey @gmantri,

Thanks for the detailed information. It looks like the failure of the API to return the relevant property is causing the pagination not possible and not a bug in client library.

As this repository is only limited to functionality of the client library, I have forwarded the query to the link below so that we may both get clarity from the relevant workload team. I will therefore close this issue for now so that we may follow it up there.

https://docs.microsoft.com/en-us/answers/questions/463543/pagination-support-for-app-role-assignments-when-b.html

**Closed by andrueastman** 2021-07-05 16:02 UTC
Labels: Needs: Attention :wave:, question
