### ISSUE TITLE
WinHttpHandler not working in recent versions of MSGraph

### ISSUE THREAD

**Issue by lgiuliani80** [microsoftgraph/msgraph-sdk-dotnet#1799] opened 2023-03-31 17:51 UTC
**Describe the bug**
Token requests fail when using WinHttpHandler as HttpClientHandler for Graph API calls.

**Exception generated**

```
Unhandled exception. System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.Net.Http.WinHttpException (80070057, 87): Error 87 calling WinHttpAddRequestHeaders, 'Parametro non corretto.'.
   at System.Net.Http.WinHttpException.ThrowExceptionUsingLastError(String nameOfCalledFunction)
   at System.Net.Http.WinHttpHandler.AddRequestHeaders(SafeWinHttpHandle requestHandle, HttpRequestMessage requestMessage, CookieContainer cookies, DecompressionMethods manuallyProcessedDecompressionMethods)
   at System.Net.Http.WinHttpHandler.StartRequestAsync(WinHttpRequestState state)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.Identity.Client.Http.HttpManager.ExecuteAsync(Uri endpoint, IDictionary`2 headers, HttpContent body, HttpMethod method, ILoggerAdapter logger, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Http.HttpManager.ExecuteWithRetryAsync(Uri endpoint, IDictionary`2 headers, HttpContent body, HttpMethod method, ILoggerAdapter logger, Boolean doNotThrow, Boolean retry, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Http.HttpManager.SendGetAsync(Uri endpoint, IDictionary`2 headers, ILoggerAdapter logger, Boolean retry, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.ExecuteRequestAsync[T](Uri endPoint, HttpMethod method, RequestContext requestContext, Boolean expectErrorsOn200OK, Boolean addCommonHeaders, Func`2 onBeforePostRequestData)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.DiscoverAadInstanceAsync(Uri endpoint, RequestContext requestContext)
   at Microsoft.Identity.Client.Instance.Discovery.NetworkMetadataProvider.SendInstanceDiscoveryRequestAsync(Uri authority, RequestContext requestContext)
   at Microsoft.Identity.Client.Instance.Discovery.NetworkMetadataProvider.FetchAllDiscoveryMetadataAsync(Uri authority, RequestContext requestContext)
   at Microsoft.Identity.Client.Instance.Discovery.NetworkMetadataProvider.GetMetadataAsync(Uri authority, RequestContext requestContext)
   at Microsoft.Identity.Client.Instance.Discovery.InstanceDiscoveryManager.FetchNetworkMetadataOrFallbackAsync(RequestContext requestContext, Uri authorityUri)
   at Microsoft.Identity.Client.Instance.Discovery.InstanceDiscoveryManager.GetMetadataEntryAsync(AuthorityInfo authorityInfo, RequestContext requestContext, Boolean forceValidation)
   at Microsoft.Identity.Client.Instance.AuthorityManager.RunInstanceDiscoveryAndValidationAsync()
   at Microsoft.Identity.Client.Internal.Requests.UsernamePasswordRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenByUsernamePasswordParameters usernamePasswordParameters, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in C:\Sviluppo\CSharp\TestBugWinHttpHandlerGraph\TestBugWinHttpHandlerGraph\Program.cs:line 13
   at Program.<Main>(String[] args)
```

**To Reproduce**

`Program.cs`:

```cs
using Microsoft.Identity.Client;

const string applicationId = "...omissis...";
const string tenantId = "...omissis...";

var app = PublicClientApplicationBuilder.Create(applicationId)
    .WithHttpClientFactory(new WinHttpMsalHttpClientFactory())
    .WithTenantId(tenantId)
    .Build();

var token = await app.AcquireTokenByUsernamePassword(
    new string[] { "https://graph.microsoft.com/.default" }, 
    "...omissis...", "...omissis...")
    .ExecuteAsync();

Console.WriteLine(token.AccessToken);

internal class WinHttpMsalHttpClientFactory : IMsalHttpClientFactory
{
    public HttpClient GetHttpClient()
    {
        if (OperatingSystem.IsWindows())
            return new HttpClient(handler: new WinHttpHandler(), true);
        else
            return new HttpClient();
    }
}
```

`MyProject.csproj`:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Identity.Client" Version="4.52.0" />
    <PackageReference Include="System.Net.Http.WinHttpHandler" Version="7.0.0" />
  </ItemGroup>
</Project>
```

**Expected behavior**
Token must be generated

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
I reported the same erroneous behaviour in Azure SDK for .NET: https://github.com/Azure/azure-sdk-for-net/issues/34664

**Comment by lgiuliani80** [comment] 2023-03-31 17:53
Problem introduced after version 4.39.0 of Microsoft.Identity.Client or version 6.0.1 of System.Net.Http.WinHttpHandler NuGet packages.

**Comment by andrueastman** [comment] 2023-04-03 07:14
Thanks for raising this @lgiuliani80 

As this seems to be caused by the authentication library(MSAL), I believe the right place to raise the issue is at link below.
Any chance you can create an issue there so that the `Microsoft.Identity.Client` library can be looked into?

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues

**Comment by lgiuliani80** [comment] 2023-04-03 18:18
> Thanks for raising this @lgiuliani80
> 
> As this seems to be caused by the authentication library(MSAL), I believe the right place to raise the issue is at link below. Any chance you can create an issue there so that the `Microsoft.Identity.Client` library can be looked into?
> 
> https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues

You are totally write. You can close this bug or put in a parking state until the bug I added on MSAL.NET, as you suggested, is addressed.

**Comment by andrueastman** [comment] 2023-04-04 07:51
We'll close this for now. Feel free to re-open incase anything comes up @lgiuliani80

**Closed by andrueastman** 2023-04-04 07:51 UTC
Labels: Needs: Attention :wave:
