### ISSUE TITLE
[Graph v5.2] Breaks Azure Storage requests

### ISSUE THREAD

**Issue by njannink** [microsoftgraph/msgraph-sdk-dotnet#1734] opened 2023-03-16 21:42 UTC
**Describe the bug**
When I update to Microsoft.Graph v5.2 i start to get exceptions from my Azure Blob storage backend. I had to rollback the nuget update to get my web-portal working again. Any idea what might be the reason for this?

```
Azure.RequestFailedException: Response x-ms-client-request-id 'b130822e-b56a-4c27-81d4-3c8f3137846e' does not match the original expected request id, '4754a551-93df-480a-8853-a5970ac36f8d'.
   at Azure.Storage.StorageRequestValidationPipelinePolicy.OnReceivedResponse(HttpMessage message)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.InnerProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.RedirectPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Storage.Blobs.ContainerRestClient.CreateAsync(Nullable`1 timeout, IDictionary`2 metadata, Nullable`1 access, String defaultEncryptionScope, Nullable`1 preventEncryptionScopeOverride, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobContainerClient.CreateInternal(PublicAccessType publicAccessType, IDictionary`2 metadata, BlobContainerEncryptionScopeOptions encryptionScopeOptions, Boolean async, CancellationToken cancellationToken, String operationName)
   at Azure.Storage.Blobs.BlobContainerClient.CreateIfNotExistsInternal(PublicAccessType publicAccessType, IDictionary`2 metadata, BlobContainerEncryptionScopeOptions encryptionScopeOptions, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobContainerClient.CreateIfNotExistsAsync(PublicAccessType publicAccessType, IDictionary`2 metadata, BlobContainerEncryptionScopeOptions encryptionScopeOptions, CancellationToken cancellationToken)
   ...
```

**Environment**
Azure App Service using AspNetCore 7.0.4
Microsoft Graph v5.2

**Comment by andrueastman** [comment] 2023-03-17 07:33
Thanks for raising this @njannink 

Any chance you could share more details on the previous version you were upgrading from to help us understand more on what could have changed?

**Comment by njannink** [comment] 2023-03-17 12:39
I upgraded from v5.0 to v5.2. With version 5 everything works fine with v5.2 I start getting these errors.

I use `Azure.Storage.Blobs` version 12.15.0

**Comment by oletolshaveics** [comment] 2023-03-17 13:44
I encountered the same error ("Response x-ms-client-request-id '785c4392-27d9-4f8f-a020-72bf9c23e0e1' does not match the original expected request id, 'e9aa8121-3c10-427e-b5aa-41db5450b109'.") when developing some new code.

I had Microsoft.Graph version 5.2.0 installed. I then downgraded to 5.1.0 and then it worked.

**Comment by njannink** [comment] 2023-03-17 14:35
Thanks good to know I'm not the only one encountering this

**Comment by andrueastman** [comment] 2023-03-20 06:10
@oletolshaveics @oletolshaveics 

There was a change in 5.2.0 to lower the dependency of System.Text.Json(https://github.com/microsoft/kiota-serialization-json-dotnet/pull/70) which is also a dependency for `Azure.Storage.Blobs`.

Any chance the error goes away if you explicitly add to your csproj?
```xml
<PackageReference Include="System.Text.Json" Version="7.0.2" />
```

**Comment by oletolshaveics** [comment] 2023-03-20 12:38
> @oletolshaveics @oletolshaveics
> 
> There was a change in 5.2.0 to lower the dependency of System.Text.Json([microsoft/kiota-serialization-json-dotnet#70](https://github.com/microsoft/kiota-serialization-json-dotnet/pull/70)) which is also a dependency for `Azure.Storage.Blobs`.
> 
> Any chance the error goes away if you explicitly add to your csproj?
> 
> ```
> <PackageReference Include="System.Text.Json" Version="7.0.2" />
> ```

Unfortunately, I am no longer able to reproduce the problem (using Microsoft.Graph 5.2). I could onlly reproduce it as part of a larger backup/restore operation, involving concurrent blob read and write operations. I did try to to re-run the old code that failed with the initial error message, but this time it worked.

I have also tried just upgrading Microsoft.Graph to 5.2 and that also works on my current main branch. I cannot rule out that the reason it works for me using 5.2 is that some other dependency is pulling in 7.0.2 of System.Text.Json. 

I will update here if I can reproduce the error, but currently it works for me using both 5.1 and 5.2 of Microsoft.Graph.

**Comment by njannink** [comment] 2023-03-20 13:15
I tried to do this but it did not  fix the issue. Where do I need to add the explicit link to 

    <PackageReference Include="System.Text.Json" Version="7.0.2" />

Next to the Graph reference or next to the `Azure.Storage.Blobs` reference

**Comment by njannink** [comment] 2023-03-20 13:42
I also tested putting the `System.Text.Json` next to the Graph import but that also didn't fix the issue. So at the moment I really can't update to MS Graph v5.2

**Comment by andrueastman** [comment] 2023-03-23 09:49
@njannink Any chance this is reproducible with an update to `v5.3.0`?

There is also the `System.Diagnostics.DiagnosticSource` that was updated to use a sliding version, Any chance adding that reference to the latest version resolves the issue?

**Comment by vedion** [comment] 2023-03-23 13:22
Related issue:
https://github.com/Azure/azure-sdk-for-net/issues/35010

**Comment by njannink** [comment] 2023-03-23 15:39
With Graph v5.3 I could not reproduce the issue so it seems to be an incompatibility between Graph v5.2 and Azure.Storage.Blobs v12.15

**Comment by andrueastman** [comment] 2023-03-23 16:29
Thanks for the feedback @njannink 

For now, we'll close this issue as it looks like it's followed up from https://github.com/Azure/azure-sdk-for-net/issues/35010. We will re-open in the event any further action is needed from Graph SDK.

**Comment by njannink** [comment] 2023-03-23 16:32
I will keep an eye on it in further updates. If it happens again I will reopen or create a new defect

**Comment by njannink** [comment] 2023-03-23 16:50
@andrueastman I was actually too quick. It took a bit longer for my DevOps release pipeline to deploy. The error is still there with v5.3. Sorry for the inconvenience

**Comment by andrueastman** [comment] 2023-03-24 06:27
Thanks for following up on this. Looks like this is resolved by updating to the latest version of Azure.Core. 
We will make a new release of https://github.com/microsoft/kiota-authentication-azure-dotnet so that the latest dependency is used.

https://github.com/Azure/azure-sdk-for-net/issues/35010#issuecomment-1481629438

Any chance this is resolved on your end if you add the latest version of Azure.Core to your project?

**Closed** 2023-03-24 10:41 UTC
Labels: Bug
