### ISSUE TITLE
Not compatible with netcoreapp1.1?

### ISSUE THREAD

**Issue by szmaorka** [microsoftgraph/msgraph-sdk-dotnet#88] opened 2017-02-22 20:55 UTC
Is that possible that it is not compatible with ASP.NET Core 1.1?

```
Package Microsoft.Graph 1.2.1 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Microsoft.Graph 1.2.1 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - portable45-net45+win8+wpa81 (.NETPortable,Version=v4.5,Profile=Profile111)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
```

**Comment by lpunderscore** [comment] 2017-02-22 21:05
It's almost here, there is a PR for it, I'm guessing they are just about to merge it soon.

https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/84

**Comment by cbales** [comment] 2017-03-02 18:56
Closing as duplicate of #49

**Closed by cbales** 2017-03-02 18:56 UTC
