### ISSUE TITLE
Latest release returns incorrect models for groups

### ISSUE THREAD

**Issue by lebartha** [microsoftgraph/msgraph-sdk-dotnet#2084] opened 2023-08-18 18:48 UTC
Hi,

Have the following code:

`var groups = await graphClient.Users[user.UserPrincipalName].MemberOf.GetAsync();`
`bool isValidUser = groups.Value.Cast<Microsoft.Graph.Models.Group>().Any...`

Version 5.22.0 returns the types of the elements correctly, Microsoft.Graph.Models.Group.
Latest version 5.23.0 returns the types as Microsoft.Graph.Models.DirectoryObject and fails to make the cast.

Exception:
System.InvalidCastException: 'Unable to cast object of type 'Microsoft.Graph.Models.DirectoryObject' to type 'Microsoft.Graph.Models.Group'.'

Stack Trace:
at System.Linq.Enumerable.<CastIterator>d__97`1.MoveNext()   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)   at CaptivaApi.Helper.Utilities.IsAuthorized(String groupList) in W:\Source Code\Azure GitHub\ds-capture-dashboard-webapi\CaptivaApi\Helper\Utilities.cs:line 493

See attached screenshots.

![Screenshot 2023-08-18 at 11 20 47 AM](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/22775963/cdf73941-f117-4fca-9125-626cc1f71635)
![Screenshot 2023-08-18 at 11 29 33 AM](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/22775963/ed43e5fc-c9df-4ddc-8b5f-78a5ee16d4a4)

***
Latest version of Visual Studio 2022 (17.7.1)
.NET Framework 4.8
Windows 11

**Comment by MartinM85** [comment] 2023-08-21 05:08
After the change in `DirectoryObject.CreateFromDiscriminatorValue`, I'm facing similar issue.

Maybe better solution instead of casting group on the client is to request server side casting

`var groups = await graphClient.Users[user.UserPrincipalName].MemberOf.GraphGroup.GetAsync();`

**Comment by andrueastman** [comment] 2023-08-21 06:46
Thanks for raising this @lebartha 

As @MartinM85 mentioned, this is caused by the change in `DirectoryObject.CreateFromDiscriminatorValue`. This should be resolved in the next in the course of the week.

**Comment by lebartha** [comment] 2023-08-21 15:08
Awesome. Thank you, that is good news!

**Closed** 2023-08-23 12:17 UTC
Labels: Bug, P1
