### ISSUE TITLE
Temporary tokens issued by graph api is invalid - again

### ISSUE THREAD

**Issue by bokmadsen** [microsoftgraph/msgraph-sdk-dotnet#267] opened 2018-05-02 08:08 UTC
This is same thing again as #257 
Please fix this ASAP @ificator

**Comment by bokmadsen** [comment] 2018-05-02 11:25
Is there any update? This is very urgent!!

**Comment by mlafleur** [comment] 2018-05-02 15:08
I'm going to close this since #257 was also reopened and it seems best to keep the reapearence of this issue in the same thread. A new issue can be opened if it turns out to have a different root cause.

**Closed by mlafleur** 2018-05-02 15:08 UTC
